### ISSUE TITLE
"Fatal error: __toString() must not throw an exception" when expectation fails

### ISSUE THREAD

**Issue by jurajseffer** [sebastianbergmann/phpunit-mock-objects#111]
I have a mocked object with __toString() method that should get called during my test exactly 4 times (scripts does echo on it).

```php
$response
->expects($this->exactly(4))
->method('__toString')
->will($this->returnValue("foo"));
```

I kept getting
**PHP Fatal error:  Method Mock_Response_64f18545::__toString() must not throw an exception in ...**
when expectation failed, i.e. __toString() wasn't executed 4 times.

Can this be somehow improved so we avoid the fatal error and notify the user of failed expectation instead? It wasn't obvious to me where the exception during __toString is coming from.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
