### ISSUE TITLE
Add option to emit a warning when non-existant classes/interfaces/methods are stubbed/mocked

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-mock-objects#12]

**Comment by Tobion** [comment]
@sebastianbergmann considering #296 has been implemented I think this one should be implemented as well. Then it is consistent that you get a warning when trying to mock a non-existing method or class.
That non-existing classes are created on-the-fly as empty classes without any method is alot of magic that hides potential problems.

**Comment by sebastianbergmann** [comment]
This has been taken care of in PHPUnit 5.4. Just use `createMock()`.

**Comment by Tobion** [comment]
@sebastianbergmann this is not correct. You can still create mocks of non-existing classes:

`$mock= $this->createMock('NonExistingClass');` will not create a warning or error.

**Comment by Tobion** [comment]
Nvm, I used a class that was magically defined with `getMockBuilder` before which of course succeded.

**Comment by Tobion** [comment]
I've found sebastianbergmann/phpunit#2228 which is really bad IMO.
