### ISSUE TITLE
Test Proxies

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-mock-objects#132]
## Background

Thanks to [Gerard Meszaros](http://www.gerardmeszaros.com/), we have the following (names for) categories of [test doubles](http://xunitpatterns.com/Test%20Double.html):
- [Dummy](http://xunitpatterns.com/Dummy%20Object.html)
- [Fake](http://xunitpatterns.com/Fake%20Object.html)
- [Stub](http://xunitpatterns.com/Test%20Stub.html)
- [Spy](http://xunitpatterns.com/Test%20Spy.html)
- [Mock](http://xunitpatterns.com/Mock%20Object.html)

Of these, PHPUnit has had built-in support for [stubs](http://phpunit.de/manual/current/en/test-doubles.html#test-doubles.stubs) and [mocks](http://phpunit.de/manual/current/en/test-doubles.html#test-doubles.mock-objects) for quite some time.

The stubs and mocks generated by PHPUnit(_MockObject) can be used in every context where an object of the original class is expected. As it should be, the code of the original class is not executed when a method is called on the stub or mock.
## Motivation for Test Proxies

When writing integration tests in general and edge-to-edge tests in particular, you generally do not want to stub or mock dependencies. Sometimes, though, the ability to have expectations such as "this method has to be called with these arguments for this test to be successful" would also be useful in tests that have a larger scope than unit tests.

The idea is to have a "Test Proxy" object that provides the same API for expectations as a mock object while at the same time [proxying](https://en.wikipedia.org/wiki/Proxy_pattern) method calls to the original class.
## Usage Example

**Foo.php**

``` php
<?php
class Foo
{
    public function doSomething(Bar $bar)
    {
        return $bar->doSomethingElse();
    }
}
```

**Bar.php**

``` php
<?php
class Bar
{
    public function doSomethingElse()
    {
        return 'result';
    }
}
```

**FooTest.php**

``` php
<?php
class FooTest extends PHPUnit_Framework_TestCase
    public function testSomething()
    {
        $proxy = $this->getMockBuilder('Bar')
                      ->enableProxyingToOriginalMethods()
                      ->getMock();

        $proxy->expects($this->once())
              ->method('doSomethingElse');

        $foo = new Foo;
        $this->assertEquals('result', $foo->doSomething($proxy));
    }
}
```

**Comment by nickhen** [comment]
Sorry for the stupid question, but I am a newbie to phpunit. Are phpunit Proxies considered to be Dummy, Fake, Stub, Mock, or Spy objects???? Thanks!
