### ISSUE TITLE
setMockClassName will not work with namespaces

### ISSUE THREAD

**Issue by gsuess** [sebastianbergmann/phpunit-mock-objects#134]
## Description ##

When building a mock object with a class name that is in a namespace a Parse error will occur.

## How to reproduce ##

Run the following test case with phpunit 3.7.19:

```php
<?php
class MyClass {

}


class TestCase extends \PHPUnit_Framework_TestCase {

	function build_mock($name) {
		return 	$this->getMockBuilder('MyClass')
			->setMockClassName($name)
			->getMock();
	}

	function assertCorrectMock($name) {
		$this->assertInstanceOf($name, $this->build_mock($name));
	}

	function test_works() {
		$this->assertCorrectMock('MyMock');
	}


	function test_fails() {
		$this->assertCorrectMock('MyNamespace\MyMock');
	}
}
```

## Expected result ##

Both tests pass.

## Actual result ##

Only test works passes. The other gives the following output:

```
PHPUnit 3.7.19 by Sebastian Bergmann.

.PHP Parse error:  syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '{' in /usr/share/php/PHPUnit/Framework/MockObject/Generator.php(231) : eval()'d code on line 1
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:176
PHP   5. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/TextUI/TestRunner.php:349
PHP   6. PHPUnit_Framework_TestSuite->runTest() /usr/share/php/PHPUnit/Framework/TestSuite.php:745
PHP   7. PHPUnit_Framework_TestCase->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:775
PHP   8. PHPUnit_Framework_TestResult->run() /usr/share/php/PHPUnit/Framework/TestCase.php:776
PHP   9. PHPUnit_Framework_TestCase->runBare() /usr/share/php/PHPUnit/Framework/TestResult.php:648
PHP  10. PHPUnit_Framework_TestCase->runTest() /usr/share/php/PHPUnit/Framework/TestCase.php:831
PHP  11. ReflectionMethod->invokeArgs() /usr/share/php/PHPUnit/Framework/TestCase.php:976
PHP  12. TestCase->test_fails() /usr/share/php/PHPUnit/Framework/TestCase.php:976
PHP  13. TestCase->assertCorrectMock() /home/user/test.php:25
PHP  14. TestCase->build_mock() /home/user/test.php:16
PHP  15. PHPUnit_Framework_MockObject_MockBuilder->getMock() /home/user/test.php:12
PHP  16. PHPUnit_Framework_TestCase->getMock() /usr/share/php/PHPUnit/Framework/MockObject/MockBuilder.php:130
PHP  17. PHPUnit_Framework_MockObject_Generator::getMock() /usr/share/php/PHPUnit/Framework/TestCase.php:1318
PHP  18. PHPUnit_Framework_MockObject_Generator::getObject() /usr/share/php/PHPUnit/Framework/MockObject/Generator.php:216
PHP Fatal error:  Class 'MyNamespace\MyMock' not found in /usr/share/php/PHPUnit/Framework/MockObject/Generator.php on line 237
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:176
PHP   5. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/TextUI/TestRunner.php:349
PHP   6. PHPUnit_Framework_TestSuite->runTest() /usr/share/php/PHPUnit/Framework/TestSuite.php:745
PHP   7. PHPUnit_Framework_TestCase->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:775
PHP   8. PHPUnit_Framework_TestResult->run() /usr/share/php/PHPUnit/Framework/TestCase.php:776
PHP   9. PHPUnit_Framework_TestCase->runBare() /usr/share/php/PHPUnit/Framework/TestResult.php:648
PHP  10. PHPUnit_Framework_TestCase->runTest() /usr/share/php/PHPUnit/Framework/TestCase.php:831
PHP  11. ReflectionMethod->invokeArgs() /usr/share/php/PHPUnit/Framework/TestCase.php:976
PHP  12. TestCase->test_fails() /usr/share/php/PHPUnit/Framework/TestCase.php:976
PHP  13. TestCase->assertCorrectMock() /home/user/test.php:25
PHP  14. TestCase->build_mock() /home/user/test.php:16
PHP  15. PHPUnit_Framework_MockObject_MockBuilder->getMock() /home/user/test.php:12
PHP  16. PHPUnit_Framework_TestCase->getMock() /usr/share/php/PHPUnit/Framework/MockObject/MockBuilder.php:130
PHP  17. PHPUnit_Framework_MockObject_Generator::getMock() /usr/share/php/PHPUnit/Framework/TestCase.php:1318
PHP  18. PHPUnit_Framework_MockObject_Generator::getObject() /usr/share/php/PHPUnit/Framework/MockObject/Generator.php:216
```

**Comment by eps90** [comment]
Hey, any news about it? I'd say it's kind of **critical** bug. @AubreyHewes I see you have some solution for this, does it work? Can you make a PR with that?

**Comment by sebastianbergmann** [comment]
I am tryinto to understand the issue (again): why do you need to set the name of the mocked class and why does it matter in which namespace it is?

**Comment by gsuess** [comment]
There are many use cases for determining an object's class namespace in order to find it's friends. PHP permits reading the namespace at runtime and hence runtime can depend on the namespace. If the unit test set mock class into a different namespace, test may incorrectly fail as a result.

**Comment by sebastianbergmann** [comment]
That does not make any sense to me at all, sorry.

**Comment by eps90** [comment]
Correct me if I'm wrong. But currently I write tests for some legacy code to make easy refactor after. Let's leave the anti-patterns topics for now, it's just an example.
Let's assume I have a part of an application that for given class name in string checks if that class exists and if does extend another (surely existing) class.
```php
// ...
$className = 'MyNamespace\\' . $className;

if (class_exists($className)) {
    $instance = new $className;
    if (!($instance instanceof MyAbstractClass)) {
        throw new \Exception("The class must extend MyAbstractClass");
   }
}
```
So to create a mock of non-existing class I have to create mock of `MyAbstractClass` and give it a name passed as a string in production code:
```php
$this->getMockBuilder('MyAbstractClass')
    ->setClassName('MyNamespace\MyClass')
    ->getMock();

$this->assertTrue(class_exists('MyAbstractClass'));
$this->assertTrue(class_exists('MyNamespace\MyClass'));

// if I'd assign mock to variable $mock
$this->assertInstanceOf('MyAbstractClass', $mock);
$this->assertInstanceOf('MyNamespace\MyClass', $mock);
```
And with that I can create some testing methods for non existing classes, existing ones, extending and non-extending `MyAbstractClass`.
Once again - correct me if I'm wrong. Maybe my tests should look like differently.

**Comment by eps90** [comment]
In the other hand, there is some pretty simple albeit not that clean workaround: create class alias dynamically:
```php
$this->getMockBuilder('MyAbstractClass')
    ->setClassName('MyClass')
    ->getMock();
class_alias('MyClass', 'MyNamespace\MyClass`);
```
But I think it's a bit risky, since you already have class named `MyNamespace\MyClass`.

**Comment by AubreyHewes** [comment]
@eps90 not all tests are yet refactored ;-) so fork is not _yet_ provable; will not be creating a pr
@sebastianbergmann setting the namespace is sometimes required when testing code that also looks at the classname/namespace... in our case a legacy mvc framework that gets its template directory from the class hierarchy of the controller...

**Comment by rayward** [comment]
Factories often create objects located in a particular namespace. Being able to specify the namespace of a mock would make testing the factory easier.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
