### ISSUE TITLE
callback() for parameter called twice

### ISSUE THREAD

**Issue by spako** [sebastianbergmann/phpunit-mock-objects#181]
This is related to sebastianbergmann/phpunit#749

When a callback is used for an expected parameter it is being verified twice. Once on method invocation and again when the mock class is verified.

This caused problems for me when the same instance was a parameter for two different methods. When the mock is then verified, the latest parameter version was used my my assertions failed.

`enableArgumentCloning()` did not help.

I implemented a "quick fix" that will only allow `PHPUnit_Framework_MockObject_Matcher_Parameters::verify()` to run through once, the second time it is called it will just return `true`. I don't know if this breaks anything else, but it solved my issue.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
