### ISSUE TITLE
expects $matcher unexpected by-ref behaviour

### ISSUE THREAD

**Issue by JeroenDeDauw** [sebastianbergmann/phpunit-mock-objects#183]
Seen on PHPUnit 4.1.1 and 4.1.3.

I had some test code as follows:

```php
$storeWriter = $this->getMock( 'Wikibase\QueryEngine\QueryStoreWriter' );
$storeWriter->expects( $this->exactly( iterator_count( $entityIterator ) ) )
	->method( 'updateEntity' );
$reporter = $this->getMock( 'Wikibase\QueryEngine\Importer\ImportReporter' );
$reporter->expects( $this->exactly( iterator_count( $entityIterator ) ) )
	->method( 'onEntityInsertStarted' );
```

And changed it to

```php
$aCallForEachEntity = $this->exactly( iterator_count( $entityIterator ) );

$storeWriter = $this->getMock( 'Wikibase\QueryEngine\QueryStoreWriter' );
$storeWriter->expects( $aCallForEachEntity )
	->method( 'updateEntity' );

$reporter = $this->getMock( 'Wikibase\QueryEngine\Importer\ImportReporter' );
$reporter->expects( $aCallForEachEntity )
	->method( 'onEntityInsertStarted' );
```

That fails, unless I pass in a clone to the second `expects` call. This was unexpected to me, and might be something that can be improved.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
