### ISSUE TITLE
Arguments passed by reference are not verifed properly

### ISSUE THREAD

**Issue by FritsvanCampen** [sebastianbergmann/phpunit-mock-objects#196]
Related to: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/116
Tested in: 3.7.35

The difference between this case and 116 is that I changed `any()` for `once()` (update: and removed some unrelated fluff).

Full test case:

	<?php
	class Foo {
		public function bar(&$a) {}
	}
	
	class Test extends PHPUnit_Framework_TestCase {
		public function testCallback() {
			$foo = $this->getMockBuilder('Foo')->getMock();
	
			$a = 0;
	
			$foo->expects($this->once())
				->method('bar')
				->with($a)
				->will($this->returnCallback(array($this, 'myCallback')));
	
			$foo->bar($a);
	
			$this->assertEquals(1, $a);
		}
	
		public static function myCallback(&$a) {
			$a = 1;
		}
	}

Current output:

    PHPUnit_Framework_ExpectationFailedException : Expectation failed for method name is equal to <string:bar> when invoked 1 time(s).
    Parameter 0 for invocation Foo::bar(1) does not match expected value.
    Failed asserting that 1 matches expected 0.

Expected output: test passing

---

I have done some debugging and if you change:

    ->with($a)

by:

    ->with($this->callback(function ($a) { return $a === 0; }))

If you put a break point on `callback` you will see that it gets called 3 times (and then fails). The first **two** times `$a` is `0`, then `myCallback` gets called and then `callback` gets called again (and fails).

Is there a reason why `callback` gets called more than once? Why does PHPUnit need to verify the arguments _twice_? Update: I found this: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/181

**Comment by christoph-schlosser** [comment]
I am also experiencing this issue with basically the same test case.

Running phpunit 4.1.0 with php 5.5.24

The test succeeded until i switched the parameters to be passed by reference. I manually debugged it and noticed, that the test itself runs successfully to the last line of code and after it has basically completed, apparently the parameters for the method calls are checked again but (obviously) have changed in the meantime which then causes the test to fail.

If i manually set an incorrect value, i get a stacktrace while with this delayed check failing i do not get a stacktrace.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
