### ISSUE TITLE
Mock object method expectation counter not incremented when an exception is thrown

### ISSUE THREAD

**Issue by Infthitbox** [sebastianbergmann/phpunit-mock-objects#203]
I have the following test code:
```php
<?php

class ExpectException {

  public function process($condition) {

    if ($this->A($condition)) {
      return;
    }

    $this->B();
  }

  public function A($condition) {
    if ($condition) {
      return TRUE;
    }
    return FALSE;
  }

  private function B() {
    throw new TestException();
  }
}

class TestException extends Exception{
}

```

And the following test class:
```php
<?php

include_once('./ExpectException.php');

class ExpectExceptionTest extends PHPUnit_Framework_TestCase {
/**
 * @expectedException TestException
 */
  public function testProcessException() {
    $expect_exception = $this->getMock('\ExpectException');
    $expect_exception->expects($this->once())
      ->method('B');
    $expect_exception->process(FALSE);
  }
}
```

I expect that this test should pass, since method 'B' will throw the exception I'm looking for when it is executed. Instead, this is the result: 

PHPUnit 4.3.1 by Sebastian Bergmann.

F

Time: 27 ms, Memory: 3.75Mb

There was 1 failure:

1) ExpectExceptionTest::testProcessException
Expectation failed for method name is equal to <string:B> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.

Additional information:

$ phpunit --version
PHPUnit 4.3.1 by Sebastian Bergmann.

$ php --version
PHP 5.5.9-1ubuntu4.4 (cli) (built: Sep  4 2014 06:56:34) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

It also appears that this issue was reported for a previous version of phpunit and was marked as fixed: 

http://osdir.com/ml/php.phpunit.devel/2008-07/msg00018.html

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
