### ISSUE TITLE
the exception thrown when mocking static method should have a message

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit-mock-objects#206]
https://github.com/sebastianbergmann/phpunit-mock-objects/blob/96c5b81f9842f38fe6c73ad0020306cc4862a9e3/src/Framework/MockObject/Generator/mocked_static_method.tpl.dist is throwing an exception when a static method is mocked and called. However, no message is passed in the exception (and the exception itself does not set a default one).
This makes it quite hard to understand what goes wrong when this exception happens in a test. See https://travis-ci.org/symfony-cmf/BlockBundle/jobs/40057684#L245 for such case. There is no way to know the issue except by searching the source to find where the exception is used.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
