### ISSUE TITLE
setMethods() seems irrelevant

### ISSUE THREAD

**Issue by edsonmedina** [sebastianbergmann/phpunit-mock-objects#209]
In the manual 

> setMethods(array $methods) can be called on the Mock Builder object to specify the methods that
> are to be replaced with a configurable test double. The behavior of the other methods is not
> changed. If you call setMethods(null), then no methods will be replaced.

But if you skip setMethods() and do:

    $mock= $this->getMockBuilder('Foo')
		        ->getMock();
    
    $mock->expects($this->once())->method('foo')->with('bar');

It'll just work fine. 

Same for stubs.

So what's the use of setMethods()? The documentation needs to be clearer.

**Comment by whatthejeff** [comment]
All methods are mocked by default. `setMethods()` allows you to limit which methods are mocked to the ones you've specified.

**Comment by edsonmedina** [comment]
Hum, I see.

So to clarify:
* If no `setMethods()` is used, all the methods return `null`, unless mocked
* If `setMethods()` is used, all methods keep the original behaviour except the ones specified

Is that right?

**Comment by whatthejeff** [comment]
:+1: Correct

**Comment by edsonmedina** [comment]
So what the method actually does is "mirror all the original methods except x".
Not the best naming IMO.

**Comment by whatthejeff** [comment]
Agreed.

**Comment by edsonmedina** [comment]
And you can only set expectations on methods IF you use setMethods(). 
Is that correct?

**Comment by whatthejeff** [comment]
If you don't call `setMethods()`, you can set expectations on all methods. If you do call `setMethods()`, you can only set expectations on the specified methods. From the [documentation](https://phpunit.de/manual/current/en/test-doubles.html):

> By default, all methods of the original class are replaced with a dummy implementation that just returns null (without calling the original method)

...

> `setMethods(array $methods)` can be called on the Mock Builder object to specify the methods that are to be replaced with a configurable test double. The behavior of the other methods is not changed. If you call `setMethods(null)`, then no methods will be replaced.

**Comment by whatthejeff** [comment]
Closing this since it's unlikely that we'll make API changes at this point. Feel free to open an issue in [sebastianbergmann/phpunit-documentation](https://github.com/sebastianbergmann/phpunit-documentatio) regarding how the documentation for this method could be improved.
