### ISSUE TITLE
Method arguments are lost if multiple interface mocking

### ISSUE THREAD

**Issue by szicsu** [sebastianbergmann/phpunit-mock-objects#213]
#### TestCase
```php
$this->getMock(array(
    '\\SplObserver',
    '\\SplSubject'
));
```

#### Output
```
PHP Fatal error:  Declaration of Mock_SplSubject_e68eca62::update() must be compatible with SplObserver::update(SplSubject $SplSubject) in (...)/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(335) : eval()'d code on line 11
```

#### Info
```bash
$ phpunit --version
PHPUnit 4.4.4 by Sebastian Bergmann.

$ php -v
PHP 5.6.4-1+deb.sury.org~trusty+1 (cli) (built: Dec 31 2014 21:13:54) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans

```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
