### ISSUE TITLE
[HHVM] Cannot mock abstract classes which don't fully implement an interface

### ISSUE THREAD

**Issue by colinodell** [sebastianbergmann/phpunit-mock-objects#223]
I'm experiencing an issue which seems to be caused by commit c684a8a and/or HHVM.  I'm essentially unable to mock an abstract class which doesn't fully implement an interface.

You can replicate the issue by defining an interface with two methods:

~~~php
interface TestInterface
{
    public function foo();

    public function bar();
}
~~~

And then create an abstract instance which only implements one of the methods:

~~~php
abstract class AbstractTestClass implements TestInterface
{
    public function foo()
    {
        return 'foo';
    }
}
~~~

Running a test like this fails:

~~~php
$mock = $this->getMockForAbstractClass('AbstractTestClass');
$this->assertEquals('foo', $mock->foo());

// Fatal error: Class Mock_AbstractTestClass_727654a9 contains abstract method (bar) and must therefore be declared abstract or implement the remaining methods
~~~

This behavior only occurs when using 2.3.1 on HHVM (I'm using 3.6.1).  2.3.0 works just fine because it doesn't contain commit d4cc5f0b.  Also, this behavior does not seem to occur in PHP on 2.3.1.

**Comment by colinodell** [comment]
Oops, that's the wrong error message.  One moment, let me fix that.

**Comment by colinodell** [comment]
Error message has been corrected:

> Fatal error: Class Mock_AbstractTestClass_727654a9 contains abstract method (bar) and must therefore be declared abstract or implement the remaining methods

You can see a real-world instance of this occurring [in my project's Travis build](https://travis-ci.org/thephpleague/commonmark/jobs/58317957#L180):

* [The test](https://github.com/thephpleague/commonmark/blob/master/tests/Extension/ExtensionTest.php)
* [The interface](https://github.com/thephpleague/commonmark/blob/master/src/Extension/ExtensionInterface.php)
* [Abstract method](https://github.com/thephpleague/commonmark/blob/master/src/Extension/Extension.php), implementing everything except for `getName()`

**Comment by colinodell** [comment]
Yeah, this looks like an HHVM issue.  You could either wait until it's fixed or (temporarily) revert that change.

**Comment by Tobion** [comment]
+1

**Comment by sgolemon** [comment]
@colonodell Not knowing the innards of PHPUnit, I'm unclear why this is an HHVM issue.  Is Mock_AbstractTestClass_727654a9 declaring a bar method? If not then it has to be abstract.. that's working-as-intended as far as I can see from here...

**Comment by sgolemon** [comment]
Nevermind, looks like @fredemmott already looked into it and it's been fixed in the 3.8 branch.
https://twitter.com/fredemmott/status/609034548328976384

**Comment by dave1010** [comment]
It looks like this was fixed in hhvm by this: https://github.com/facebook/hhvm/commit/b786320582e086630bbeb65043c3be5680257ba0

I haven't verified this yet.

**Comment by colinodell** [comment]
@sgolemon HHVM contained a bug in their `ReflectionClass` implementation: https://github.com/facebook/hhvm/issues/5170
