### ISSUE TITLE
Insufficient error message when getting InvalidArgumentException by calling MockBuilder::setMethods() with wrong parameters

### ISSUE THREAD

**Issue by sustmi** [sebastianbergmann/phpunit-mock-objects#224]
Example test:
```
<?php

class ExampleTest extends PHPUnit_Framework_TestCase {
    public function testExample() {
        $mock = $this->getMockBuilder('stdClass')
            ->setMethods('__construct') // not an array
            ->disableOriginalConstructor()
            ->getMock();
    }
}
```
Gives the following error output in CLI:
```
There was 1 error:

1) ExampleTest::testExample
InvalidArgumentException: 

/<path>/ExampleTest.php:8
```

Imagine that you had all the method call on one line. It would be even more difficult to tell what is the problem.

The exception is thrown in `PHPUnit_Framework_MockObject_Generator::getMock()`, but this information gets filtered out by `PHPUnit_Util_Filter::getFilteredStacktrace()` (using `PHPUnit_Util_Blacklist`).

I know that there are reasons why PHPUnit's internals are filtered out, but could you add some sane message when throwing the `InvalidArgumentException`?

**Comment by sustmi** [comment]
PR https://github.com/sebastianbergmann/phpunit-mock-objects/pull/225 tries to solve the problem.

**Comment by sustmi** [comment]
Maybe even better: PR https://github.com/sebastianbergmann/phpunit-mock-objects/pull/226

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
