### ISSUE TITLE
Generator::getObjectForTrait is not using $callOriginalConstructor argument

### ISSUE THREAD

**Issue by juliendufresne** [sebastianbergmann/phpunit-mock-objects#230]
Hello,

It seems that we cannot give any argument to the getObjectForTrait method.

Use case:
```php
trait SimpleTrait
{
    public $property;

    public function __construct($property)
    {
        $this->property = $property;
    }
}

class SimpleTraitTest extends PHPUnit_Framework_TestCase
{
    public function testConstruct()
    {
        $mock = $this->getObjectForTrait('SimpleTrait', ['value']);
        $this->assertEquals('value', $mock->property);
    }
}
```

**Comment by juliendufresne** [comment]
In my opinion this is something really easy to fix without any drawbacks
We only have to specify the arguments in https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Generator.php#L483

I can create a PR if you'd like.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
