### ISSUE TITLE
PHPUnit unable to find class

### ISSUE THREAD

**Issue by Baachi** [sebastianbergmann/phpunit-mock-objects#231]
Hey guys, 

i discovered a bug in the phpunit mocking library. i was trying to mock the class `Doctrine\ODM\MongoDB\Mapping\ClassMetadata` but phpunit says `PHPUnit_Framework_MockObject_RuntimeException: Class  does not exist`.

Please note that this bug only occurs in php 5.3. 

Here is the travis build https://travis-ci.org/ddeboer/data-import/builds/47457455 and the PR which shows the bug https://github.com/ddeboer/data-import/pull/83.

**Comment by smilesrg** [comment]
+1 for resolving this issue!

**Comment by sebastianbergmann** [comment]
Please provide a minimal, self-contained, reproducing example. Also note that support for PHP 5.3 will soon be dropped.

**Comment by smilesrg** [comment]
Maybe this would help?
https://travis-ci.org/ddeboer/data-import/jobs/47457456

**Comment by sebastianbergmann** [comment]
It does not as it is 1) not self-contained and 2) uses an outdated version of PHPUnit.

**Comment by smilesrg** [comment]
@sebastianbergmann please close this issue, after updating PHPUnit everything works well.
