### ISSUE TITLE
Regression in 2.3.2 when mocking classes that use traits

### ISSUE THREAD

**Issue by markstory** [sebastianbergmann/phpunit-mock-objects#232]
The 2.3.2 release introduced a regression that creates fatal errors when generating mocks from classes that have complex uses of traits. This blew up in the [CakePHP CI builds](https://travis-ci.org/cakephp/cakephp/jobs/64418482). Because that is a quite a bit of code, I made a self contained example that reproduces the issue.

```php
<?php
trait BaseTrait {
    protected function hello() {
        return 'hello';
    }
}

trait ChildTrait {
    use BaseTrait {
        hello as private hi;
    }

    protected function hello()
    {
        return 'hi';
    }

    protected function world()
    {
        return $this->hi();
    }
}

class Subject {
    use ChildTrait;

    public function speak()
    {
        return $this->world();
    }
}


class TestCase extends PHPUnit_Framework_TestCase
{
    public function testSpeak()
    {
        $mock = $this->getMock('Subject', [], []);
    }
}
```

I think the issue is caused by ChildTrait redefining hello() and also aliasing the same method in a base trait.

**Comment by enkrates** [comment]
We saw a similar problem with mocking \Predis\Client with 2.3.2 this morning. I haven't looked at the internals of that class, but the above example code is exactly the same kind of code we had that threw an error. Something along the lines of:

```php
$client = $this->getMock('Predis\Client');
```

Works fine with 2.3.1, error in 2.3.2.

**Comment by sebastianbergmann** [comment]
The regression was caused by https://bugs.php.net/bug.php?id=69180.

**Comment by markstory** [comment]
Thanks @sebastianbergmann :smile:
