### ISSUE TITLE
Method signature for mock method fails

### ISSUE THREAD

**Issue by burzum** [sebastianbergmann/phpunit-mock-objects#234]
I'm getting a signature error when mocking one of my objects in the test:

See https://travis-ci.org/burzum/cakephp-search-plugin/jobs/66534571

```
1) Burzum\Search\Test\TestCase\Controller\Component\PrgComponentTest::testInitialize
Declaration of Mock_Request_c2cdb747::method() should be compatible with Cake\Network\Http\Request::method($method = NULL)
/home/travis/build/burzum/cakephp-search-plugin/tests/TestCase/Controller/Component/PrgComponentTest.php:29
```

My test case is here https://github.com/burzum/cakephp-search-plugin/blob/develop/tests/TestCase/Controller/Component/PrgComponentTest.php#L24

```php
$this->request = $this->getMockBuilder('\Cake\Network\Http\Request')
            ->setMethods(['is'])
            ->getMock();
```

I've been told by @lorenzo that he reported this some time ago as well and it was fixed, he said it's probably a regression. See https://github.com/sebastianbergmann/phpunit-mock-objects/issues/159

The issue was fixed in **4.0** of phpunit according to Jose, I'm using **4.5**. I've tested 4.0 as well and getting the same issue. As a workaround I just mocked the method with the failing signature as well and its working now.

Originally opened here https://github.com/sebastianbergmann/phpunit/issues/1746

**Comment by GrahamCampbell** [comment]
There is no 4.0 or 4.5 release of phpunit-mock-objects?

**Comment by sebastianbergmann** [comment]
Why would there be? The whole point of separate components is separate release cycles.

**Comment by sebastianbergmann** [comment]
Please provide a minimal, self-contained, reproducing example.

**Comment by burzum** [comment]
@GrahamCampbell  it's the actual phpunit version that requires whatever version of phpunit-mock-objects, I haven't investigated from which submodule this comes from.

@sebastianbergmann what exactly do you want? A full unit tests? Honestly I'm a bit lost and short on time to figure this out. Just mock any class, don't much a method that gets called somewhere else and you should get the problem.

**Comment by sebastianbergmann** [comment]
I understand that you are short on time. And I don't have the time to clone your repo, figure out how to run your test suite, and then debug this in the context of your plugin and the framework the plugin is for. That is why I asked for a minimal, self-contained, reproducing example.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
