### ISSUE TITLE
Mock more than one interface at once

### ISSUE THREAD

**Issue by fabiocarneiro** [sebastianbergmann/phpunit-mock-objects#235]
https://github.com/sebastianbergmann/phpunit/issues/1504

```php
$this->getMock(array());
```
Sometimes there are methods in many interfaces and you must use them together to proper test something.

Nowadays we must create a test asset of an interface that extends the required interfaces and use this asset in the mock.

Alternative:
```php
$this->getExtensionMock(array());
```

**Comment by sebastianbergmann** [comment]
This already works:

```php
<?php
interface A
{
    public function b();
}

interface C
{
    public function d();
}

class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        $stub = $this->getMock(['A', 'C']);

        $stub->method('b')->willReturn('A::b() called');
        $stub->method('d')->willReturn('C::d() called');

        $this->assertInstanceOf('A', $stub);
        $this->assertInstanceOf('C', $stub);

        $this->assertEquals('A::b() called', $stub->b());
        $this->assertEquals('C::d() called', $stub->d());
    }
}
```

```
PHPUnit 4.7.5-9-gbc6f8c5 by Sebastian Bergmann and contributors.

.

Time: 57 ms, Memory: 5.50Mb

OK (1 test, 4 assertions)
```

Or are you asking for something else?

**Comment by fabiocarneiro** [comment]
Thanks for the reply. Actually the original request was done 7 months ago and I moved the request recently, but I didn't know it was already available or when this was implemented.

:+1:
