### ISSUE TITLE
Mocking two methods and expecting at least one of them will be called exactly once

### ISSUE THREAD

**Issue by kiler129** [sebastianbergmann/phpunit-mock-objects#236]
Hello everyone.
Testing one of my projects I found one problem which I couldn't resolve. I'm expecting that method will emit warning with certain message using PSR-complaint logger. If you look at [PSR LoggerInterface](https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php) you can see message can be printed using either `$logger->warning(...)` or `$logger->log(LogLevel::WARNING, ...)`.

I wish to test if method calls  `$logger->warning(...)` at exactly once OR `$logger->log(LogLevel::WARNING, ...)` exactly once.
How to test against that scenario?

**Comment by Darhazer** [comment]
You can achieve this by setting variable in a callback and then assert against the variable.

```php
$logCount = 0;
$logCallback = function($arg) use (&$logCount){
  $logCount++;
  return true;
};
$loggerMock->method('log')->with($this->callback($logCallback));
$loggerMock->method('warning')->with(LogLevel::WARNING, $this->callback($logCallback));
// perform action
$this->assertEquals(1, $logCount, "Logger was expected to be called 1 time, actually called $logCount times");
```

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
