### ISSUE TITLE
Mocks created with Instantiator fail tests when mocked class raises E_NOTICE, regardless of convertNoticesToExceptions setting.

### ISSUE THREAD

**Issue by mmcnickle** [sebastianbergmann/phpunit-mock-objects#237]
Version 4.2 and later use `Instantiator` for creating mocks when `disableOriginalConstructor()` is used.

If the class being mocked raises an `E_NOTICE`, an exception is raised and the test fails, regardless of the phpunit `convertNoticesToExceptions` flag. Prior to version 4.2 this was not the case.

I realise this will require a change to the Instantiator component upstream, as its custom error handler around unserialization (https://github.com/doctrine/instantiator/blob/master/src/Doctrine/Instantiator/Instantiator.php#L154-L162) is not configurable, but filing here as it's a regression in the behaviour of phpunit.

Suppressing the `E_NOTICE` in Instantiator's custom error handler allows the test to pass.

`phpunit.xml`
````xml
<phpunit convertNoticesToExceptions="false"></phpunit>
````

`NoticeTestCase.php`
````php
<?php

include 'NoticeClass.php';

class NoticeClassTestCase extends PHPUnit_Framework_TestCase {

	public function testMockNoticeClass() {
		$mock = $this->getMockBuilder('\NoticeClass')
			->disableOriginalConstructor()
			->getMock();
	}

}
````

`NoticeClass.php`

````php
<?php

class NoticeClass {

	protected $params = array(
		bad_key => 1,
		'good_key' => 2
	);

}
````

Test output (*v.4.5.0*)
````
❯ vendor/bin/phpunit NoticeTestCase.php 
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /vagrant/tests/phpunit.xml

E

Time: 40 ms, Memory: 7.00Mb

There was 1 error:

1) NoticeClassTestCase::testMockNoticeClass
PHPUnit_Framework_MockObject_RuntimeException: Use of undefined constant bad_key - assumed 'bad_key'

/vagrant/tests/NoticeTestCase.php:10

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
````

Test output (*v4.1.6*)
````
❯ phpunit NoticeTestCase.php 
PHPUnit 4.1.6 by Sebastian Bergmann.

Configuration read from /vagrant/tests/phpunit.xml

.

Time: 4 ms, Memory: 6.75Mb

OK (1 test, 0 assertions)
````

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
