### ISSUE TITLE
__toString() cannot be added to mock after it's creation

### ISSUE THREAD

**Issue by kiler129** [sebastianbergmann/phpunit-mock-objects#240]
Let's start with simples class possible:

```php
class A {}
```

Than add hypothetical test, which require `A` mock:
```php
class BTest extends PHPUnit_Framework_TestCase
{
    public function testFoo()
    {
        $a = $this->getMockBuilder('A')->getMock();
        $a->method('__toString')->willReturn('a');
        echo $a;
    }
}
```

Unfortunately that code doesn't work - exception `Object of class Mock_A_d8021d70 could not be converted to string` is thrown. If I try to add `__toString()` method to class `A` (it can even be empty or return anything) code prints expected value.

In my case I can use `getMock()` without `getMockBuilder()`, which is temporary workaround:
```php
class BTest extends PHPUnit_Framework_TestCase
{
    public function testFoo()
    {
        $a = $this->getMock('A', ['__toString']);
        $a->method('__toString')->willReturn('a');
        echo $a;
    }
}
```

Am I doing something wrong or it's a bug?

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
