### ISSUE TITLE
Traits with Abstract Methods Aren't Testable

### ISSUE THREAD

**Issue by Pittiplatsch** [sebastianbergmann/phpunit-mock-objects#243]
Initial note: This is no dup of sebastianbergmann/phpunit#766

I am trying to directly test the following trait:
```
trait FooTrait
{
    public function returnTrue()
    {
        return true;
    }

    /**
     * @return string
     */
    abstract protected function getFoo();
}
```
This trivial test:
```
public function test_trait()
{
    $trait = $this->getObjectForTrait(FooTrait::class);
    $this->assertTrue($trait->returnTrue());
}
```
results in:
`Fatal error: Class Trait_FooTrait_40dbdc77 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Trait_FooTrait_40dbdc77::getFoo) in .../phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(301) : eval()'d code on line 4`

**Comment by Darhazer** [comment]
Use `getMockForTrait` - it will stub  all abstract methods and you can test the concrete ones. The manual includes an example.

**Comment by Darhazer** [comment]
With PHPUnit 4.8.6 your example works with `getMockForTrait` and gives the quoted error with `getObjectForTrait`, so please check your code. If you experience the issue check your PHPUnit version.

**Comment by Pittiplatsch** [comment]
Thank you for your feedback. I'll double-check my code again, and come back then.

**Comment by Pittiplatsch** [comment]
After re-thinking I've found we have a misunderstanding here. I don't need a MOCK of the trait, but I want to directly TEST the trait - this is done by using `getObjectForTrait`.

Sorry for the confusion about which method is used whilst this is clearly stated in my method `public function test_trait()`: it's `getObjectForTrait`!

Ergo: The initial problem remains.

**Comment by Darhazer** [comment]
@Pittiplatsch I don't get the problem. It mocks only the abstract methods, which don't have implementation anyway. How otherwise you would test an abstract class, if some of the concrete methods call abstract method and the outcome depends on the return value? The only way to test abstracts IMO is by stubbing the abstract methods, e.g. by using partial mock, and that's exactly what you receive with `getMockForTrait`. If it was just an abstract class you'd use `getMockForAbstractClass`.

If `getMockForTrait` doesn't do what you expect, can you describe the expected behavior?

**Comment by Pittiplatsch** [comment]
@Darhazer To make long things short: You are completely right. `getMockForTrait` and `getMockForAbstractClass` can be used to test traits / abstract classes with abstract methods. After re-consulting the [docs] (https://phpunit.de/manual/current/en/test-doubles.html#test-doubles.mocking-traits-and-abstract-classes) ("This allows for testing the concrete methods of a trait."), everything is clear...

What I stumbled about is the fact that mocks per definitionem don't generate code coverage which obviously disqualifies them for testing the SUT itself. Maybe wording of the method names is a little bit misleading in that respect...

Thank you for your patience :-)
