### ISSUE TITLE
Mock several repositories

### ISSUE THREAD

**Issue by quentincurtet** [sebastianbergmann/phpunit-mock-objects#252]
Hi,

I am creating tests with phpunit and i need to test the return of an api so i mock the repo and the entity manager.
```
public function testLookup()
    {
        $webApp = new WebApp();
        $webApp
            ->setEnabled(true)
            ->setApiEnabled(true)
            ->setDisabledMessage('test')
            ->setHash('azertyuiopmlkjhg')
            ->setObjectClassName('Symposium\Bundle\EventBundle\Entity\Event')
            ->setObjectId(1)
        ;

        $webAppRepository = $this->getMockBuilder('\Symposium\Bundle\WebAppBundle\Repository\WebAppRepository')
            ->disableOriginalConstructor()
            ->getMock()
        ;
        $webAppRepository->expects($this->once())
            ->method('lookup')
            ->will($this->returnValue($webApp))
        ;

        $entityManager = $this->getMockBuilder('\Doctrine\Common\Persistence\ObjectManager')
            ->disableOriginalConstructor()
            ->getMock()
        ;
        $entityManager->expects($this->any())
            ->method('getRepository')
            ->will($this->returnValue($webAppRepository))
        ;

        $webAppManager = new WebAppManager($entityManager);
        $this->assertEquals($webApp, $webAppManager->lookup('site1.sp.local.fr'));
    }
```

When i use the lookup function, it calls getRepository with a repository in parameter (which is different from WebAppRepository), but my function will use the WebAppRepository and not the good one.

I want to precise that i have tested my API and it works perfectly.

Thank you for the help.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
