### ISSUE TITLE
[RFC] Allow overwriting of method return value

### ISSUE THREAD

**Issue by Darhazer** [sebastianbergmann/phpunit-mock-objects#255]
Currently if you set return value for a method, and later you set another one, the method always returns the first one. This is because it returns the value of the first matching matcher ([link to respective code](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/InvocationMocker.php#L115)), which in most cases doesn't make sense.

```php
$mock = $this->getMock('someInterface')
$mock->method('test')->willReturn(1);
$mock->method('test')->willReturn(2);
$mock->test(); // returns 1
```
Why it doesn't make sense in the majority of the cases?
First, if there is no any constraints to be matched, it's intuitive the last set value to be returned.
Even if you set different constraints (different values for `->with()` for example), the mock object will fail the test because at least one of the constraints won't be matched by the call. E.g. Even if you have multiple matchers, any of the calls should match all of the matchers' constraints. 
For such situations `returnMap`, `returnCallback`,  `onConsecutiveCalls` and `withConsecutive` are used. When you use any of those, you still have single matcher!

The only valid case in which the mock has multiple matchers, and the return value is not determined solely by the first one is the `at()` expectation. I haven't seen any situation where `at` is necessary - IMO it does more harm than good, as usually it leads to tests that are copy of the implementation. In nearly every case one of the `returnMap`, `returnCallback`,  `onConsecutiveCalls` and `withConsecutive`  solves the problem. `at()` of course has it's place - if one needs to verify the order of execution of methods. Even in this case, `withCallback` may be used as an ad-hoc approach, although I admit it would be very ugly.

It seems that the multiple matchers exists just because of `at`. `at` is a border case in my proposal. Its behavior can be preserved by specifying an interface that returns a multipleInvocationMatchers, like `expectsAt` or `expectsWithOrder`. Or maybe different calls to `expects` to overwrite the matcher, unless it's an `at` matcher.

The use cases of this proposal are actually `stub` generators, and for stubs usually the `any` matcher is used, so the proposal can go especially for this matcher. The usual use case is when 99% of the test cases use default return values, and there is only 1 that needs a different value. I usually create builders for the stub objects and provide default return values for any call, then I need to overwrite. Not having the possibility to do so makes me define all the stub methods in the builders's `build` method and forces me to call `build` in the test case even if I don't change anything. Moreover, it doesn't allow effective use of `setup` for injecting of stubs. And it's hard to debug.

Implementation may vary. An explicit method `replace` may be introduced, instead of changing the underlying code.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
