### ISSUE TITLE
The Symfony testsuite is failing with PHPUnit 5.0 while it passes in 4.8

### ISSUE THREAD

**Issue by xabbuh** [sebastianbergmann/phpunit-mock-objects#259]
Quoting @stof from sebastianbergmann/phpunit#1886:

> The tests of the Security component are failing in a mock-related assertion when using PHPUnit 5.0, while it works fine in 4.8. See https://travis-ci.org/symfony/symfony/jobs/83213024#L3477 for the failure.

**Comment by sebastianbergmann** [comment]
I still need a minimal, self-contained test case to reproduce, debug, and fix this issue.

**Comment by nicolas-grekas** [comment]
Not yet a reproducer, but a workaround in https://github.com/symfony/symfony/pull/16122

the error message is:
```
1) Symfony\Component\Security\Core\Tests\Authorization\AccessDecisionManagerTest::testStrategiesWith2Roles with data set #4 (Mock_TokenInterface_41dee6d3 Object (...), 'unanimous', Mock_VoterInterface_818611c5 Object (...), false)
Expectation failed for method name is equal to <string:vote> when invoked 2 time(s).
Method was expected to be called 2 times, actually called 1 times.
```

And it is true that `vote` is called 1 time and not 2 times btw, so I don't know if the issue is in 4.8 or 5.0. Our tests are green with the 4.8 behavior but they may need a fix...

**Comment by nicolas-grekas** [comment]
The issue is that an assertion on a mock object isn't enforced in phpunit 4 and is now enforced in 5.0, related to sebastianbergmann/phpunit#1821, which is not only about `@depends` annotations but also about data providers.
