### ISSUE TITLE
[RFC] Allow overwriting of method return value

### ISSUE THREAD

**Issue by Darhazer** [sebastianbergmann/phpunit-mock-objects#260]
Currently if you set return value for a method, and later you set another one, the method always returns the first one. This is because it returns the value of the first matching matcher (link to respective code), which in most cases doesn't make sense.

``` php
$mock = $this->getMock('someInterface')
$mock->method('test')->willReturn(1);
$mock->method('test')->willReturn(2);
$mock->test(); // returns 1
```

Why it doesn't make sense in the majority of the cases?
First, if there is no any constraints to be matched, it's intuitive the last set value to be returned.
Even if you set different constraints (different values for `->with()` for example), the mock object will fail the test because at least one of the constraints won't be matched by the call. E.g. Even if you have multiple matchers, any of the calls should match all of the matchers' constraints. 
For such situations `returnMap`, `returnCallback`, `onConsecutiveCalls` and `withConsecutive` are used. When you use any of those, you still have single matcher!

The only valid case in which the mock has multiple matchers, and the return value is not determined solely by the first one is the `at()` expectation. I haven't seen any situation where `at` is necessary - IMO it does more harm than good, as usually it leads to tests that are copy of the implementation. In nearly every case one of the `returnMap`, `returnCallback`, `onConsecutiveCalls` and `withConsecutive` solves the problem. `at()` of course has it's place - if one needs to verify the order of execution of methods. Even in this case, `withCallback` may be used as an ad-hoc approach, although I admit it would be very ugly.

It seems that the multiple matchers exists just because of `at`. `at` is a border case in my proposal. Its behavior can be preserved by specifying an interface that returns a `multipleInvocationMatchers`, like `expectsAt` or `expectsWithOrder`. Personally I would go for a ->expects(...)->method(...)->before(another method)`(or`->after(another method)`) for supporting testing of the order of execution. Another option would be different calls to expects to overwrite the matcher, unless it's an`at` matcher.

The use cases of this proposal are actually stub generators, and for stubs usually the `any` matcher is used, so the proposal can go especially for this matcher. The usual use case is when 99% of the test cases use default return values, and there is only 1 that needs a different value. I usually create builders for the stub objects and provide default return values for any call, then I need to overwrite. Not having the possibility to do so makes me define all the stub methods in the builders's build method and forces me to call build in the test case even if I don't change anything. Moreover, it doesn't allow effective use of setup for injecting of stubs. And it's hard to debug.

Implementation may vary. An explicit method `replace` may be introduced, instead of changing the underlying code. I could provide sample implementation, if the idea seems right.

**Comment by finishingmove** [comment]
Just ran into this same problem.

Your suggestion makes a lot of sense @Darhazer . It's kind of sad that this is not getting attention.

**Comment by Darhazer** [comment]
I have implemented this in [526291e](https://github.com/Darhazer/phpunit-mock-objects/commit/526291ed74a4f34c429c3289fa86ba08e2937963). It seems that `at` expectations have nothing to do this. No tests are broken after the change.

@sebastianbergmann any change you can share why the multiple matchers were implemented in the first place?

**Comment by axiac** [comment]
I think multiple matchers were designed to allow something like this:

```

// The tested code
// TestedClass::doSomething()
$first  = $this->dep->get('a', array('foo' => 'bar'));
$second = $this->dep->get('b', array('baz'));
return array_merge($first, $second);


// The test
$this->stub = $this->getMock('Dependency');
$this->stub
    ->expects(self::any())
    ->method('get')
    ->with(self::identicalTo('a'), self::anything())
    ->willReturn(array(1, 2, 3))
;
$this->stub
    ->expects(self::any())
    ->method('get')
    ->with(self::identicalTo('b'), self::anything())
    ->willReturn(array(4, 5))
;

$object = new TestedClass($this->stub);
$result = $object->doSomething();
self::assertSame(array(1, 2, 3, 4, 5), $result);
```
See the full code in [this gist](https://gist.github.com/axiac/467735db1db9992e5780).


`TestedClass::doSomething()` calls `Dependency::get()` twice, with `'a'` and `'b'` as the first argument (not necessarily in this order). The value of second argument passed to `get()` by `doSomething()` is not important for the stub. It has complex structure and putting the actual values in the stub setup makes the test brittle and difficult to read. `returnMap()`, `returnCallback()`, `onConsecutiveCalls()` cannot be used here.

Unfortunately, on the setup described above PHPUnit fails the test with the message:

```
Expectation failed for method name is equal to <string:get> when invoked zero or more times
Parameter 0 for invocation Dependency::get('a', Array (...)) does not match expected value.
Failed asserting that two strings are identical.
Expected :b
Actual   :a
```

`PHPUnit_Framework_MockObject_InvocationMocker::invoke()` checks all the matchers and remembers the value returned by the first one that matches and the last exception thrown (if any of them throw exceptions). When no exception was caught, the value returned by the first matcher that matched is returned. When exceptions are caught, the last one is re-thrown.

I think it should stop checking on the first match for both method name and parameters and re-throw the exception only if nothing matches.

**Comment by MichaelDeBoey** [comment]
I'd like to see this too!

Almost all my test will invoke a specific method, but some tests don't.

So I did this:
```
protected function setUp()
{
    $mock = $this->getMock('someInterface')
    $mock->expects($this->once())->method('specificMethod')->willReturn(true);
    $this->classUsingMock = new ClassUsingMock($mock);
}
```
And wanted to overwrite it like this:
```
public function testMethod()
{
    $mock->expects($this->never())->method('specificMethod')->willReturn(true);
    $this->classUsingMock = new ClassUsingMock($mock);
}
```

This is (like @Darhazer allready mentioned) very counter intuitive

**Comment by Darhazer** [comment]
@axiac  returnMap can be used in your setup as soon as it supports matchers as arguments (see #285)
It will become:
```
$this->stub
    ->method('get')
    ->will($this->returnValueMap(array(
        [self::identicalTo('a'), self::anything(), array(1,2,3)],
        [self::identicalTo('b'), self::anything(), array(4,5)]
    ));
```

**Comment by de-graeuler** [comment]
I need to have a parameterless method that returns different values for my tests. So returnValueMap is not an option for me, because there's no argument to match.

**Comment by Darhazer** [comment]
@de-graeuler is onConsecutiveCalls an option for you?

**Comment by de-graeuler** [comment]
@Darhazer: I would consider that a workaround. I currently call the willReturn in each testMethod. That solves it, too. That approach is preferable in my case, because the class under test is still under construction, so the order of consecutive calls may change.

Maybe some background on what I actually do might help. In the `setUp()` method of the unit tests I build PHPUnit stub objects for these helper classes and the Slim DI container. The idea is to configure the "good" behavior (for example return true) in the setUp method and then "override" the helper class methods' return value with other stuff: `willReturnValue("something else")`. 

Working demo code:
```php
<?php
// Not required for the demo, but to show how DI is mocked in my case.
// use Interop\Container\ContainerInterface;

use PHPUnit\Framework\TestCase;

class StubObjectTest extends TestCase {

    private $stub;

    public function mockMe() {
        // do some stuff.
    }
    
    protected function setUp() {
        $this->stub = $this->createMock(StubObjectTest::class);
        $this->stub->method('mockMe')->willReturn(true);

        /* 
         * Not required for the demo, but to show how DI is mocked in my case.
         * 
        $this->dataProcessor = $this->createMock(UplinkDataProcessor::class); 
        $this->container = $this->createMock(ContainerInterface::class);
        $this->container->method('get')->will($this->returnValueMap([
            // there's more here...
            ['uplinkDataProcessor', $this->dataProcessor]
            ]));
        * $this->container is then used as constructor param for the classes method under test.
        */
    }
    
    /**
     * @expectedException Exception
     */
    public function testExceptionCall() {
        $this->stub->method('mockMe')->willThrowException(new \Exception("message"));
        $this->stub->mockMe();
    }

    public function testSuccessfullCall() {
        $this->assertTrue($this->stub->mockMe());
    }
    
    /**
     * This test demos my desired usage. It fails, because mockMe still returns true.
     */
    public function testModifiedReturnValue() {
        $this->stub->method('mockMe')->willReturn(false);
        $this->assertFalse($this->stub->mockMe(), 
                "mockMe is expected to return false after calling willReturn(false).");
    }
}
?>
```

PHPUnit Test Result:
```
PHPUnit 5.6.8 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.28 with Xdebug 2.5.0rc1
Configuration: P:\software\backend\phpunit.xml

..F                                                                 3 / 3 (100%)

Time: 820 ms, Memory: 5.50MB

There was 1 failure:

1) StubObjectTest::testModifiedReturnValue
mockMe is expected to return false after calling willReturn(false).
Failed asserting that true is false.

P:\software\backend\test\graeuler-garden-collect\StubObjectTest.php:55

FAILURES!
Tests: 3, Assertions: 3, Failures: 1.
```
When you call the willReturn() in the testMethod itself it works:
```php
<?php

use PHPUnit\Framework\TestCase;

class StubObjectTest extends TestCase {

    private $stub;

    public function mockMe() {
        // do some stuff.
    }
    
    protected function setUp() {
        $this->stub = $this->createMock(StubObjectTest::class);
    }
    
    /**
     * @expectedException Exception
     */
    public function testExceptionCall() {
        $this->stub->method('mockMe')->willThrowException(new \Exception("message"));
        $this->stub->mockMe();
    }

    /**
     * Call willReturn(true) directly in the test, now.
     */
    public function testSuccessfullCall() {
        $this->stub->method('mockMe')->willReturn(true);
        $this->assertTrue($this->stub->mockMe());
    }
    
    /**
     * Now it works.
     */
    public function testModifiedReturnValue() {
        $this->stub->method('mockMe')->willReturn(false);
        $this->assertFalse($this->stub->mockMe(), 
                "mockMe is expected to return false after calling willReturn(false).");
    }
}
?>
```

Successfull PHPUnit run:
```
PHPUnit 5.6.8 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.28 with Xdebug 2.5.0rc1
Configuration: P:\software\backend\phpunit.xml

...                                                                 3 / 3 (100%)

Time: 820 ms, Memory: 5.75MB

OK (3 tests, 3 assertions)
```

In reality, the setUp of the DI container and helpers is already quite complex and I'm not done yet.

**Comment by marrch-caat** [comment]
Wow. So after all the discussions the problem just won't be fixed?..
