### ISSUE TITLE
callback() for parameter called too many times

### ISSUE THREAD

**Issue by sandermarechal** [sebastianbergmann/phpunit-mock-objects#261]
I am submitting this because #181 still occurs in PHPUnit 5. I have some test code like this:

```php
$mock->expects($this->exactly(2))
    ->method('myMethod')
    ->with($this->callback(function ($v) {
        var_dump($v);
    }));

$mock->myMethod('foo');
$mock->myMethod('bar');
```

The callback is called three times instead of two times.

**Comment by minterior** [comment]
Also happening in PHPUnit 4.8.15. Printing _$someParameter_ twice in the example:
```php
    public function testMe()
    {
        $this->exampleObject->expects($this->once())->method('run')
            ->with($this->callback(function ($someParameter) {
                var_dump($someParameter);
                return true;
            }));
        $this->sut->doSomething();
    }
```

**Comment by laoneo** [comment]
Happening for me to. If you put `echo new \Exception();` inside the callback then it prints that it is called once from the _PHPUnit_Framework_TestCase->runTest();_ function and the second time from _PHPUnit_Framework_TestCase->verifyMockObjects();_. Perhaps this information helps to find a solution for that issue.

**Comment by balther74** [comment]
This is also causing an issue if you are checking an object against an expected object and the original object is later changed, (in my case I am setting properties on an object and ensuring the object passed to the persistence mock is what I expect but I then have to update and attached object).

A working example is given below

```PHP
<?php
class MockFailTest extends PHPUnit_Framework_TestCase
{
    public function testUpdateObject(){
        $initialObject = new stdClass();
        $initialObject->name='Initial Name';
        $expectedObject = new stdClass();
        $expectedObject->name='Expected Name';
        $mock = $this->getMockBuilder('mock')->getMock();
        $mock
            ->expects($this->once())
            ->method('persist')
            ->with($expectedObject)
            ->willReturn(true);
        $systemUnderTest = new sut($mock);

        $systemUnderTest->changeObject($initialObject);
    }
}

class sut{

    protected $mockService;

    public function __construct($mockService)
    {
        $this->mockService = $mockService;
    }

    public function changeObject($object)
    {
        $object->name = 'Expected Name';
        $this->mockService->persist($object);
        $object->name = 'Different Expected Name';
    }
}

class mock {
    public function persist($object)
    {

    }
}
```

The output is as follows
```
Expectation failed for method name is equal to <string:persist> when invoked 1 time(s).
Parameter 0 for invocation mock::persist(stdClass Object (...)) does not match expected value.
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 stdClass Object (
-    'name' => 'Expected Name'
+    'name' => 'Different Expected Name'
 )
```

As parameters are checked when they are called there should they really be verified a second time  by the verifyMockObjects() call? if so there should be able to disable that call on a per mock, per expectation or per parameter basis.

**Comment by mayko64** [comment]
Same problem happens to withConsecutive()

**Comment by kherge** [comment]
I'm seeing this issue with PHPUnit 5.3.2.

I'm using this as a workaround in the meantime.

```php
    private function callOnce(Closure $closure)
    {
        return $this->callback(
            function (...$arguments) use (&$closure) {
                static $invoked = false;

                if (!$invoked) {
                    $invoked = true;

                    return $closure(...$arguments);
                }

                return true;
            }
        );
    }
```

You can probably put that in a trait and share it with any test class that needs it.

**Comment by Trainmaster** [comment]
Experiencing the same with

```php
->withConsecutive(
    array(
        $this->callback()
    ),
    array(
        $this->callback()
    )
);

**Comment by Vinai** [comment]
Bump: just ran into this extra call with phpunit/phpunit-mock-objects version 3.2.1 with phpunit/phpunit 5.4.4

**Comment by sebastianbergmann** [comment]
Pull request welcome :)

**Comment by Vinai** [comment]
This weekend I'll try

**Comment by sebastianbergmann** [comment]
Thank you, Vinai.
