### ISSUE TITLE
Throw an error when disableOriginalConstructor() and enableProxyingToOriginalMethods() are used mutually

### ISSUE THREAD

**Issue by Toflar** [sebastianbergmann/phpunit-mock-objects#264]
As explained in https://github.com/sebastianbergmann/phpunit/issues/1913#issuecomment-148407938
Not a high priority issue but I think this would maybe save other people to search for an answer :-)

**Comment by Toflar** [comment]
Thx!

**Comment by TimothyBJacobs** [comment]
@sebastianbergmann It seems like this should not be thrown if a proxyTarget has been passed?
