### ISSUE TITLE
Trigger notice when calling a deprecated mocked method

### ISSUE THREAD

**Issue by nicolas-grekas** [sebastianbergmann/phpunit-mock-objects#271]
While doing Symfony 3.0, we learned that triggering silenced deprecation notices at run-time is a good practice: it allows ignoring them by default and not-ignoring them when needed by using a custom error handler (thus making it opt-in to enlighten the upgrade path  with these notices).

But we have an issue: when using mock objects, these notices triggered by the real implementation are not triggered. As such, it makes really hard to spot codes that need an upgrade.

I'd like to know if adding a feature like this one would be accepted on the 2.3 branch: make mock objects trigger silenced deprecation notices based on the `@deprecated` phpdoc tag?
On 2.3 because it should help people with legacy code (thus legacy php version).

**Comment by stof** [comment]
@nicolas-grekas Please open an issue on Prophecy about this, as I would vote about doing it

**Comment by nicolas-grekas** [comment]
See https://github.com/phpspec/prophecy/issues/228
