### ISSUE TITLE
Cannot mock __call method: __call() must take exactly 2 arguments, mocking __get, taking one parameter, works

### ISSUE THREAD

**Issue by simej** [sebastianbergmann/phpunit-mock-objects#275]
Even though one can mock the magic `__get` method, there is a problem with mocking the magic PHP method `__call`.

**Usage**

```
$mock = $this
    ->getMockBuilder('SomeClassToMock')
    ->disableOriginalConstructor()
    ->setMethods(['__call'])
    ->getMock();

$callBack = function($name, $args)
{
    return 'A value';
};

$mock
    ->expects($this-any())
    ->method('__call')
    ->will($this->returnCallback($callBack));
```

I am defining the `$callBack` variable to provide the 2 needed parameters for the `__call` method, however the code nevers gets past `->setMethods(['__call'])`, it simply dies there with the _"__call() must take exactly 2 arguments"_ error.

Is this desired behaviour? Considering I am able to mock the `__get` method, which takes one parameter, without a problem, I think this may be a bug.

**Comment by paolomainardi** [comment]
Same problem here

**Comment by XedinUnknown** [comment]
I also need to test something that relies on the `__call()` method. @sebastianbergmann, any ideas on how we could maybe go around this?

**Comment by imilyukov** [comment]
My ugly fix for method \PHPUnit_Framework_MockObject_Generator::evalClass ))

    /**
     * @param string $code
     * @param string $className
     */
    protected function evalClass($code, $className)
    {
        if (!class_exists($className, false)) {

            // Fixed auto-generated methods for eval's constraints
            $code = str_replace(
                [
                    '__get()',
                    '__set()',
                    '__call()',
                    '__isset()',
                    '__unset()',
                ],
                [
                    '__get($name)',
                    '__set($name,  $value)',
                    '__call($name, $arguments)',
                    '__isset($name)',
                    '__unset($name)',
                ],
                $code
            );

            eval($code);
        }
    }

**Comment by localheinz** [comment]
@simej 

Works fine for me with

```php
<?php

class MockWithMagicCall
{
    public function __call($name, $arguments)
    {
    }
}

final class CallTest extends PHPUnit\Framework\TestCase
{
    public function testFoo()
    {
        $value = 'bar';

        $mock = $this->createPartialMock(MockWithMagicCall::class, [
            '__call',
        ]);

        $mock
            ->expects($this->once())
            ->method('__call')
            ->willReturnCallback(function($name, $args) use ($value) {
                return $value;
            });

        $this->assertSame($value, $mock->foo());
    }
}
```

and

```
$ ./phpunit tests/CallTest.php

PHPUnit 6.1-g43007142f by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.3
Configuration: /Users/am/Sites/sebastianbergmann/phpunit/phpunit.xml

.                                                                   1 / 1 (100%)

Time: 57 ms, Memory: 4.00MB

OK (1 test, 1 assertion)
```
