### ISSUE TITLE
Problem with PHP 7 return type declarations and mock objects

### ISSUE THREAD

**Issue by marklocker** [sebastianbergmann/phpunit-mock-objects#283]
I've just ran into a problem when mocking an object which looks to be related to PHP 7 return type declarations.

I have an object which implements an interface like this:

    <?php

    namespace Example\Namespace;

    use Example\Collection;

    interface ExampleInterface
    {
        public function exampleMethod(int $id) : Collection;
    }

When mocking an object that implements this interface, I get the following error:

    PHP Fatal error:  Declaration of Mock_Example_62b1a36c::exampleMethod(int $id) must be compatible with Example\Namespace\ExampleInterface::exampleMethod(int $id): Example\Collection in /project/path/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(291) : eval()'d code on line 1

Looking at the code that's being passed into `eval()`, I can see that it's the code for `Mock_Example_62b1a36c `, but it's missing the return type declaration on the `exampleMethod()` method - hence the error.

I'm hoping that someone familiar with this area of mock object generation can see a quick fix for this.

**Comment by sebastianbergmann** [comment]
Which version of PHPUnit are you using?

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:

```php
<?php
interface ExampleInterface
{
    public function exampleMethod(int $id) : Collection;
}

class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        $this->getMock(ExampleInterface::class);
    }
}
```

```
$ phpunit Test
PHPUnit 5.1.2 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 28 ms, Memory: 4.00Mb

OK (1 test, 0 assertions)
```

**Comment by marklocker** [comment]
Turns out it was running through an old version of PHPUnit (~4.0), thanks to a private Packagist repo misbehaving!

I'm now on 5.1.2, and like you, it runs perfectly! Thanks for checking it out.

**Comment by AGmakonts** [comment]
For all of those that still struggle with this problem, even on newer version of php unit, check if you are not using old version of PHP 7 (I had this problem on 7.0.0-dev and upgrading to 7.0.1 resolved the issue).

**Comment by KonstantinKolodnitsky** [comment]
Even though I have php7.0.8 and 
Codeception PHP Testing Framework v2.2.3
Powered by PHPUnit 5.4.8 by Sebastian Bergmann and contributors
I'm getting this issue

    [Symfony\Component\Debug\Exception\FatalErrorException]
    Declaration of Mockery_1_App_Models_Blah::addUser(App\Models\User $them, string $persona = NULL): 
    Mockery_1_App_Models_Blah must be compatible with App\Models\Blah::addUser(App\Models\User $them, string $persona = NULL):
    App\Models\Blah

P.S. Laravel 5.2

**Comment by KonstantinKolodnitsky** [comment]
Installing Mockery dev-master has helped.
