### ISSUE TITLE
Mocking HHVM method cause syntax error

### ISSUE THREAD

**Issue by slashmili** [sebastianbergmann/phpunit-mock-objects#288]
I am using HHVM 3.10.1

These is my test:

```
<?hh //partial

class Foo
{
    public function bar(Vector<Pair<string, string>> $keyValues) {
    }
}
class HackLangMockMethodTest extends \PHPUnit_Framework_TestCase
{
    public function testGetAllShouldCallCoreServiceGetAll() : void
    {
        $mockedFoo = $this->getMock(
            'Foo',
            ['bar'],
            [],
            '',
            false
        );
        $mockedFoo->expects($this->once())
            ->method('bar')
            ->willReturn(true);
    }
}
```

When I run test:

```
./bin/phpunit HackLangMockMethodTest.hh
PHPUnit 4.7.6 by Sebastian Bergmann and contributors.

Fatal error: syntax error, unexpected '<', expecting '&' or T_VARIABLE or ... in vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(290)(c8958ed20b9673e9ba9ba7cc3e28dc54) : eval()'d code on line 11
E

Time: 5.27 seconds, Memory: 10.01Mb

There was 1 error:

1) HackLangMockMethodTest::testGetAllShouldCallCoreServiceGetAll
PHPUnit_Framework_MockObject_RuntimeException: The provided class "Mock_Foo_6731b64e" does not exist

HackLangMockMethodTest.hh:18

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.

```

This test used to work HHVM 3.9. It's started failing when we upgraded our HHVM.

I debug the issue and find out that up to HHVM 3.9, they didn't implement `hasType` method on `ReflectionParameter` and `MockObject_Generator` has a way to handle in case `ReflectionParameter->hasType` is not implemented. However they have introduced `hasType` in HHVM 3.10.

So what's the deal? `MockObject_Generator` uses `ReflectionParameter` to extract the methods information. Here is the catch, Because `ReflectionParameter` can extract the correct method type, in my case it extracts `Vector<Pair<string, string>>` as the type and then later tries to `eval` the generated code with correct type. However since eval gets triggered from `MockObject_Generator` in php and this syntax is not valid for PHP, the test fails with `syntax error`

I have a patch to fix it and need your help to review it, I'll create PR for that

**Comment by nicolas-grekas** [comment]
@slashmili can you please open a PR?

**Comment by slashmili** [comment]
@nicolas-grekas This is PR: https://github.com/sebastianbergmann/phpunit-mock-objects/pull/289

**Comment by sebastianbergmann** [comment]
HHVM is no{t|longer} supported.
