### ISSUE TITLE
Feature request: As a user I want getMockBuilder() to throw PHPUnit_Util_InvalidArgumentHelper if I pass an invalid class name as $type

### ISSUE THREAD

**Issue by connerbw** [sebastianbergmann/phpunit-mock-objects#293]
Today I had strange a bug that returned a very unhelpful "Syntax error undeclared {" exception followed by a bunch of more unhelpful "Autogenerated_Class_HASH not found" exceptions.The source of my bug was `$this->getMockBuilder( ' \Foo\Bar' )-> ... // Accidental leading space character.`

First, I preemptively agree, this is my fault and not a bug. But!

[The current code](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Generator.php#L143) checks for valid $type. The $type check could be improved . [From the PHP manual](http://php.net/manual/en/language.oop5.basic.php):

> A valid class name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: ^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$.

For my request it would also have to check for valid Namespace character (\)

Thank you for your time.

**Comment by sebastianbergmann** [comment]
To avoid this kind of problem please consider using the `::class` constant that was [introduced in PHP 5.5](https://thephp.cc/news/2013/06/php-5-5-new-class-constant).
