### ISSUE TITLE
3.2.0 breaks phpunit 5.3.*

### ISSUE THREAD

**Issue by nickel715** [sebastianbergmann/phpunit-mock-objects#308]
We have installed phpunit `5.3.*` via composer. 
Today we got an update of `phpunit-mock-objects` to version 3.2.0. 
Since the update we get the following error in the tests: 

    Fatal error: Call to undefined method FooTest::registerMockObject() in vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/MockBuilder.php on line 120

Maybe it will help to set phpunit as required dependency in phpunit-mock-objects's composer.json? At the moment as I see, phpunit is only defined as dev dependency.

**Comment by sebastianbergmann** [comment]
Should be fixed via https://github.com/sebastianbergmann/phpunit/commit/5b4db518532b68c97e0baeaf7b59106e324c9f4f

**Comment by rodush** [comment]
I was just about to +1 :-)

**Comment by malkusch** [comment]
I'm also in with 5.2.12, 5.1.7 and 5.0.10.  The weird thing: I have a historic build where said PHPUnit version [passed](https://travis-ci.org/php-mock/php-mock-phpunit/builds/136551889) and now a current situation where the same version on the same code [fails](https://travis-ci.org/php-mock/php-mock-phpunit/builds/137720020) with said error.

**Comment by rodush** [comment]
I think restricting version for mock-objects in your specific project is the best option for older versions of PhpUnit. I did it for my case as well.
Upgrading to the newer version would be a better choice, of course 😉
