### ISSUE TITLE
Cannot configure protected method when using setMethodsExcept

### ISSUE THREAD

**Issue by bradynpoulsen** [sebastianbergmann/phpunit-mock-objects#314]
I am using PHPUnit 5.4.6 on PHP 7.0.8 with Xdebug v2.4.0 enabled

I am receiving a warning exception

```
1) SampleTest::testHelloWorld
Trying to configure method "doSomething" which cannot be configured because it does not exist, has not been specified, is final, or is static
```

when I execute the follow TestCase utilizing the setMethodsExcept option, which I commonly do to make isolated testing more explicit.

``` php
<?php
declare(strict_types=1);

class Sample
{
    public function helloWorld() : string
    {
        return 'Hello, ' . $this->doSomething();
    }

    protected function doSomething() : string
    {
        return 'foo';
    }
}

class SampleTest extends PHPUnit_Framework_TestCase
{
    public function testHelloWorld()
    {
        $sample = $this->getMockBuilder(Sample::class)->setMethodsExcept(['helloWorld'])->getMock();
        $sample->expects($this->once())->method('doSomething')->willReturn('World!');

        $this->assertEquals('Hello, World!', $sample->helloWorld());
    }
}
```

**Comment by bradynpoulsen** [comment]
This is caused by the [generator](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Generator.php#L1251-L1255) where it explicitly whitelists public or abstract methods only. I can execute the same test using `->setMethods(['doSomething'])` and it does not throw that warning.

**Comment by drewlachlan** [comment]
+1

**Comment by rulatir** [comment]
Which release version of PHPUnit did this fix land in?

**Comment by sebastianbergmann** [comment]
@rulatir This ticket is still open.

**Comment by bradynpoulsen** [comment]
@rulatir I closed the PR mentioned above since I wasn't maintaining it and didn't get any feedback as to whether it was in the right direction or not

**Comment by marcaddeo** [comment]
This still appears to be an issue, at least with PHPUnit `6.5.12`

**Comment by visavi** [comment]
Yes, I also care about this problem
