### ISSUE TITLE
ReturnValueMap strict value mapping does not match different objects with same value

### ISSUE THREAD

**Issue by mmikitka** [sebastianbergmann/phpunit-mock-objects#318]
I am using PHPUnit version 4.8.24

With strict comparison in the following section of PHPUnit_Framework_MockObject_Stub_ReturnValueMap two objects with the same underlying value do not equate.

``` php
public function invoke(PHPUnit_Framework_MockObject_Invocation $invocation)
{
...
    if ($invocation->parameters === $map) {
        return $return;
}
```

If I change the strict operator, "===", to "==" the test passes.

I adapted the ReturnValueMap example from the 4.8 documentation as follows.

**SomeClass.php**

``` php
<?php
class SomeClass
{
    public function doSomething()
    {
        // Do something.
    }
}
?>
```

**StubTest.php**

``` php
<?php
require_once 'SomeClass.php';

class StubTest extends PHPUnit_Framework_TestCase
{
    public function testReturnValueMapStub()
    {
        // Create a stub for the SomeClass class.
        $stub = $this->getMockBuilder('SomeClass')
                     ->getMock();

        // Create a map of arguments to return values.
        $dateParam = new \DateTime("2016-07-19 00:00:00");
        $map = array(
          array($dateParam, TRUE),
        );

        // Configure the stub.
        $stub->method('doSomething')
             ->will($this->returnValueMap($map));

        // $stub->doSomething() returns different values depending on
        // the provided arguments.
        $this->assertEquals(TRUE, $stub->doSomething($dateParam));
        $this->assertEquals(TRUE, $stub->doSomething(new \DateTime("2016-07-19 00:00:00")));
    }
}
?>
```

**Expected value**

```
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

.

Time: 57 ms, Memory: 5.25Mb

OK (1 test, 2 assertions)
```

**Actual value**

```
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

F

Time: 57 ms, Memory: 5.50Mb

There was 1 failure:

1) StubTest::testReturnValueMapStub
Failed asserting that null matches expected true.

/home/mmikitka/Desktop/phpunit/StubTest.php:25

FAILURES!
Tests: 1, Assertions: 2, Failures: 1.
```

**Comment by micguo** [comment]
I also found the same problem. But simply change "===" to "==" may break a lot of existing tests (2 == '2'). I wish we can add a flag or something.

**Comment by Darhazer** [comment]
The problem is that DateTime is not a value object, as 
`new \DateTime("2016-07-19 00:00:00") === new \DateTime("2016-07-19 00:00:00")`
returns false

I [have provided an implementation of ReturnValueMap](https://github.com/sebastianbergmann/phpunit-mock-objects/pull/285) that can use Constraints as a keys, for example

> $map = array(
>   array($this->equalsTo($dateParam), TRUE),
> );

**Comment by courtney-miles** [comment]
I have hit this problem also.  I had experimented with using `$this->equalsTo()`, since it's a convention in other places, but obviously did not work.

So I'm very pleased @Darhazer has introduced that interface in #285.  I hope it does not take too long get to accepted and released.

**Comment by PeteDevoy** [comment]
I think I hit this same problem, so in case it helps anybody else, I decided to use `$this->returnCallback` instead.

## Example

The context is I am inserting a SaleOrder object into the database and if `insert` method receives `$saleOrderIn` it should mock return `$saleOrderOut` which is the same object but with a `id` property set (e.g. of the new DB record):

```php
        //mock repo to return correct result
        /*
        $map = [
            [$saleOrderIn, $saleOrderOut]
        ];
        */
        $this->stub_repo
            ->method('insert')
            //->will($this->returnValueMap($map));
            ->will($this->returnCallback(
                function ($saleOrder) use ($saleOrderIn, $saleOrderOut) {
                    if ($saleOrder == $saleOrderIn) {
                        return $saleOrderOut;
                    }
                }
            ));
```
