### ISSUE TITLE
No longer possible to configure methods for the mock a class that does not exist

### ISSUE THREAD

**Issue by greg0ire** [sebastianbergmann/phpunit-mock-objects#322]
Since 3.2.4, using `getMock` on a class that does not exist no longer allows specifying methods that should be recognized. Calling a method on such a mock results in an undefined index warning.

This can be reproduced thanks to @nubs by following the steps described here : https://gist.github.com/nubs/ddb081e1d1b09541d7f7a1d93d009533

**Comment by sebastianbergmann** [comment]
Classes that do not exist cannot be doubled using the new `createMock()` API:
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    public function testClassThatDoesNotExistCanBeDoubledUsingMockBuilder()
    {
        $o = $this->createMock('DoesNotExist');

        $this->assertInstanceOf('DoesNotExist', $o);
    }
}
```
```
$ phpunit Test
PHPUnit 5.5.2-9-g88f407a by Sebastian Bergmann and contributors.

W                                                                   1 / 1 (100%)

Time: 19 ms, Memory: 4.00MB

There was 1 warning:

1) Test::testClassThatDoesNotExistCanBeDoubledUsingMockBuilder
Cannot stub or mock class or interface "DoesNotExist" which does not exist

WARNINGS!
Tests: 1, Assertions: 0, Warnings: 1.
```

Classes that do not exist can still be doubled using the Mock Builder API:
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    public function testClassThatDoesNotExistCanBeDoubledUsingMockBuilder()
    {
        $o = $this->getMockBuilder('DoesNotExist')->getMock();

        $this->assertInstanceOf('DoesNotExist', $o);
    }
}
```
```
$ phpunit Test
PHPUnit 5.5.2-9-g88f407a by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 21 ms, Memory: 4.00MB

OK (1 test, 1 assertion)
```
What is currently broken, and what I think this ticket is about, is configuring methods for test doubles of classes that do not exist:
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    public function testClassThatDoesNotExistCanBeDoubledUsingMockBuilder()
    {
        $o = $this->getMockBuilder('DoesNotExist')
                  ->setMethods(['someMethod'])
                  ->getMock();
    }
}
```
```
PHPUnit 5.5.2-9-g88f407a by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 19 ms, Memory: 4.00MB

There was 1 error:

1) Test::testClassThatDoesNotExistCanBeDoubledUsingMockBuilder
Undefined index: someMethod

/home/sb/Test.php:8

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```
This is a bug that I will fix ASAP.

**Comment by sebastianbergmann** [comment]
Seems to be related to this change https://github.com/sebastianbergmann/phpunit-mock-objects/commit/a8c81f22e712d7e8da4a794e6411dcf0877549dc#diff-64dbbc1c21f9be2d92e2b715617ffe34R839 by @sawmurai for #319.

**Comment by greg0ire** [comment]
Sorry, I failed to express it clearly but this is indeed the issue I wanted to report

**Comment by sebastianbergmann** [comment]
No worries, glad we figured it out now :-)

**Comment by sebastianbergmann** [comment]
@sawmurai Can you have a look at this, please? Thanks!

**Comment by sawmurai** [comment]
Sorry guys I was busy the entire day. Is there anything left to do? What was/is the outcome of this one?

**Comment by greg0ire** [comment]
I think the todo list is the following:

- [ ] put [the above failing test case](https://github.com/sebastianbergmann/phpunit-mock-objects/issues/322#issuecomment-241975750) under version control
- [ ] make it pass
- [ ] optionally, maybe in the same PR maybe not, and if it is not already done, document the fact that you can ask PHPUnit to create a mock from a class that does not exist

**Comment by sebastianbergmann** [comment]
As of db55f4b7c1c54ca6553acd0223ff52b5254895dc that test is already in `master`.

**Comment by sawmurai** [comment]
https://github.com/sebastianbergmann/phpunit-mock-objects/pull/323

Here you go guys. Tests now work for me.

**Comment by greg0ire** [comment]
Apparently this test was not enough, see #324

**Comment by sebastianbergmann** [comment]
@sawmurai Can you have another look, please? Thanks!

**Comment by sawmurai** [comment]
This should help: https://github.com/sebastianbergmann/phpunit-mock-objects/pull/325

I hope that we caught everything, now :)

**Comment by sebastianbergmann** [comment]
Thanks!
