### ISSUE TITLE
throwing exception doesn't work on mock object

### ISSUE THREAD

**Issue by rezamarandi** [sebastianbergmann/phpunit-mock-objects#337]
hi , i'm trying to create mock and throw new exception on specific inputs , but my seems like something goes wrong
here is my code -> https://gist.github.com/rezamarandi/8f07f274610b1f5a55328715fb07967b

![screen shot 2016-11-16 at 10 01 34 am](https://cloud.githubusercontent.com/assets/1782425/20337047/d1838a12-abe3-11e6-93a0-f27a6765d1a0.png)

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by rezamarandi** [comment]
@sebastianbergmann , thanks for your short time notice .
what do you mean by **minimal, self-contained, reproducing test case** ?

**Comment by nikhilkuria** [comment]
@rezamarandi to help identify your problem, we should have means to reproduce it.

It's much easier if you paste a snippet of code which I can run in my machine and would be able to reproduce your code. With this, anyone will be able to work on the issue without contacting you for fine details. 

Have a look at https://github.com/sebastianbergmann/phpunit-mock-objects/issues/358 to see a sample. Hope this helps!

**Comment by sebastianbergmann** [comment]
No feedback, closing.
