### ISSUE TITLE
Mocks of interfaces with nullable return types throw an error when returning null

### ISSUE THREAD

**Issue by jbaron-gingco** [sebastianbergmann/phpunit-mock-objects#338]
* phpunit/phpunit: 5.6.5
 * phpunit/phpunit-mock-objects: 3.4.1
 * php: 7.1.0RC6

Here's a minimal example:

Interface to mock:

    <?php
    declare(strict_types = 1);

    namespace Example\PhpUnitTest;

    interface ExampleInterface
    {
        public function foo(): ?\stdClass;
    }

Test:

    <?php
    declare(strict_types = 1);

    namespace Example\PhpUnitTest\Test;

    use Example\PhpUnitTest\ExampleInterface;

    class ExampleInterfaceTest extends \PHPUnit_Framework_TestCase
    {
        /**
         * @test
         */
        public function myTest()
        {
            $exampleMock = $this->createMock(ExampleInterface::class);
            $exampleMock
                ->method('foo')
                ->willReturn(null);

            static::assertNull($exampleMock->foo());
        }
    }

The test errors with this message:

>TypeError: Return value of Mock_ExampleInterface_71d23622::foo() must be an instance of stdClass, null returned

**Comment by sebastianbergmann** [comment]
@prolic Can you have a look?

**Comment by jbaron-gingco** [comment]
Thank you! :-)

**Comment by elegos** [comment]
I'm sorry to bother, but I've tried installing phpunit/phpunit-mock-objects 3.4.2 (which should contain this fix) over a PHPUnit 5.7.2 installation via composer (expliciting with `"phpunit/phpunit-mock-objects": "3.4.2"`), but I continue having the issue. What should I do exactly to fix this? I've tried installing even phpunit/phpunit 6.0.x, but I think it doesn't have this fix yet (same problem)... thanks :)

**Comment by sebastianbergmann** [comment]
Yes, that would be the difference. Please report issues with Prophecy in the Prophecy issue tracker.
