### ISSUE TITLE
->willReturnReference() will not return a reference

### ISSUE THREAD

**Issue by chkt** [sebastianbergmann/phpunit-mock-objects#343]
Hi,

i've been having problems getting ->willReturnReference() to actually return a reference to the supplied object. My mock has been looking somewhat like this:

```php
$reference = new Something();

$mockedObject = $this
    ->getMockBuilder(MockedTrait::class)
    ->setMethods([ 'returnReference' ])
    ->getMockForTrait();

$mockedObject
    ->expects($this->once())
    ->method('returnReference')
    ->willReturnReference($reference);
```

It may well be that I oversaw something, although my not so cursory google search came up empty. I did some digging inside the code and am under the impression that mocked methods are simply not capable of returning references at all.

[PHPUnit_Framework_MockObject_Stub_ReturnReference](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Stub/ReturnReference.php) says:

```php
class PHPUnit_Framework_MockObject_Stub_ReturnReference extends PHPUnit_Framework_MockObject_Stub_Return
{
    public function __construct(&$value)
    {
        $this->value = &$value;
    }
}
```
but it does not override the ->invoke() method of [PHPUnit_Framework_MockObject_Stub_Return](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Stub/Return.php), which returns $this->value by value.

[mocked_method.tpl.dist](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/Generator/mocked_method.tpl.dist):

```php
{modifier} function {reference}{method_name}({arguments_decl}){return_delim}{return_type}
    {{deprecation}
        $arguments = array({arguments_call});
        $count     = func_num_args();

        if ($count > {arguments_count}) {
            $_arguments = func_get_args();

            for ($i = {arguments_count}; $i < $count; $i++) {
                $arguments[] = $_arguments[$i];
            }
        }

        $result = $this->__phpunit_getInvocationMocker()->invoke(
            new PHPUnit_Framework_MockObject_Invocation_Object(
                '{class_name}', '{method_name}', $arguments, '{return_type}', $this, {clone_arguments}
            )
        );

        return $result;
}
```
 mentions a {reference} template variable, but I could not figure out how to configure the mock to use it. If I replace it manually with an ampersand and supply the missing method in PHPUnit_Framework_MockObject_Stub_ReturnReference the mocked object starts returning a reference to the object supplied to ->willReturnReference() as expected, although ideally the line `$result = $this->__phpunit_getInvocationMocker()->invoke(` should also pass by reference instead of value if I understand the workings of the code right.

Can somebody with more experience with the framework please confirm this or tell me what I'm doing wrong?

Thanks.

**Comment by lstrojny** [comment]
I am the original contributor of the feature and I see now how my choice of naming creates this problem. `willReturnReference` will not return *by reference* but rather will return whatever reference is passed. The use case is to be able to use `setUp()` to, well, set up mocks and then just reassign special properties in the test itself.
