### ISSUE TITLE
Is it possible to assert that a mock object is cloned?

### ISSUE THREAD

**Issue by courtney-miles** [sebastianbergmann/phpunit-mock-objects#348]
Apologies if this is not the correct forum for questions about using PHPUnit mocks.

I would like to know if it's possible to assert that a mock object has been cloned.

I would like to assert this as a part of testing that deep-cloning of an object is correctly implemented.

**Comment by pr0nbaer** [comment]
Code right from my mind (errors inclusive ;) ):
```php
$mock = self::getMockBuilder(MyObject::class)->setMethods(['__clone', 'otherMethodINeed'])->getMock();
$mock->expects($this->once())->method('__clone');
```
