### ISSUE TITLE
Allow configuration (without warning) of method calls handled by __call()

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-mock-objects#367]
For a class such as
```php
/**
 * @method string foo()
 */
class Example
{
    public function __call($methodName, $arguments)
    {
        return 'string';
    }
}
```
using `createMock()`
```php
class ExampleTest extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $stub = $this->createMock(Example::class);
        
        $stub->method('foo')->willReturn('bar');
    }
}
```
results in a warning
```
Trying to configure method "foo" which cannot be configured because it does not exist, has not been specified, is final, or is static
```
"Methods" "implemented" using `__call()` (or rather messages that are handled by `__call()`) currently have to be explicitly specified:
```php
class ExampleTest extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $stub = $this->getMockBuilder(Example::class)->setMethods(['getString'])->getMock();

        $stub->method('getString')->willReturn('result');
        
        $this->assertEquals('result', $stub->getString());
    }
}
```
It would be nice if PHPUnit could automatically generate the parameter for `setMethods()` by looking at the information in the docblock.

Not only for BC reasons, this new functionality should be implemented in a new convenience wrapper around the mock builder.

Moved here from https://github.com/sebastianbergmann/phpunit/issues/2679.

**Comment by spriebsch** [comment]
Is it not possible to mock __call() directly?

By mocking the methods that __call() anwers to, you'd pretty much re-write the body of __call() in the mock, and there is virtually no guarantee (not even with regards to the method signature) that the mock's behaviour resembles the behaviour of the original method.

With PHP 7 becoming more and more type-safe, people should refrain from relying on __call() anyway.
