### ISSUE TITLE
TypeError: md5() expects parameter 1 to be string, integer given

### ISSUE THREAD

**Issue by kevindh89** [sebastianbergmann/phpunit-mock-objects#374]
I'm using **PHP 7.1.5** with **strict_types** enabled.
With this setup, I get a TypeError when I try to create Mock objects with the MockBuilder.

After some searching I found this change: https://github.com/sebastianbergmann/phpunit-mock-objects/commit/a23b761686d50a560cc56233b9ecf49597cc9118

The PHP documentation states that ``mt_rand`` returns an ``int`` and ``microtime`` returns ``mixed`` while ``md5`` expects a ``string``.

* http://php.net/manual/en/function.microtime.php
* http://php.net/manual/en/function.mt-rand.php
* http://php.net/manual/en/function.md5.php

I'm not sure what the solution for this issue should be. When there are good suggestions, I might fix it myself. For now I'll use an earlier version that doesn't contain the change to ``mt_rand``.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by kevindh89** [comment]
I'm sorry, I just found out that it was caused by a configuration in my IDE that automatically added ``declare(strict_types=1)`` to the files of the phpunit-mock-objects project.

I'll close the issue.
