### ISSUE TITLE
Add Stub_ReturnCallback with invocation object bound to closure

### ISSUE THREAD

**Issue by SilverFire** [sebastianbergmann/phpunit-mock-objects#379]
It may be useful to bind closure to the invocation object, so `$this` in closure will reference that object.

Sample implementation is [available here](https://github.com/hiqdev/php-merchant/blob/346224f617a19e9fc7b9517ee6be097fe68de0b5/tests/phpunit/PHPUnit_Framework_MockObject_Stub_ReturnCallbackWithInvocationScope.php). In case idea is acceptable, I will prepare a PR.

**Comment by sebastianbergmann** [comment]
Can you explain what problem you want to solve here? Thanks!

**Comment by SilverFire** [comment]
Hello, Sebastian. The suggested class solved my problem of badly designed code (in 3-rd party package, for example) unit testing. I know it's not the best idea to unit-test dependencies and mock their private methods, but there are cases when we really need to do something unusual to ensure stability :)
