### ISSUE TITLE
Can I please have Invocation::setParameters()

### ISSUE THREAD

**Issue by malkusch** [sebastianbergmann/phpunit-mock-objects#390]
Hi

I have a [library](https://github.com/php-mock/php-mock-phpunit) which extents phpunit to mock PHP functions. This library has to remove a parameter from an invocation. This could be easily done in [phpunit-mock-objects-4](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/4.0.4/src/Invocation/Static.php#L57), but in v5 there's no public interface for that.

Could I kindly ask to add PHPUnit\Framework\MockObject\Invocation::setParameters(array)? I would happily provide a PR.

**Comment by sebastianbergmann** [comment]
Can you elaborate why what you need is no longer possible?

**Comment by malkusch** [comment]
Ok in short I need to remove one argument from the invocation. That's no more possible as there's no public API to do that. In v4 there was the public $parameters field. Now it's private and there's only a getParameters() on the interface. That's the technical explanation.

Now about my use case: That library I'm maintaining is about mocking functions with the PHPUnit API. It was a long way to get this right for every edgne case (references, varargs and optional parameters) and one step on that way was detecting arguments with default values and removing them from the invocation.

**Comment by sebastianbergmann** [comment]
It was wrong that `PHPUnit_Framework_MockObject_Invocation_Static::$parameters` and other attributes were `public` before. This change will not be reverted.

`PHPUnit_Framework_MockObject_Invocation_Static` (now `PHPUnit\Framework\MockObject\Invocation\StaticInvocation`) is a private implementation detail of `phpunit-mock-objects` (which in turn is a private implementation detail of PHPUnit) that should not be manipulated outside the scope of `phpunit-mock-objects`. This is why I am reluctant to add the mutator method you ask for.

Are you absolutely sure that you cannot achieve what you need to achieve without manipulating `PHPUnit\Framework\MockObject\Invocation` objects?

**Comment by sebastianbergmann** [comment]
@malkusch Do you have any feedback for me?

**Comment by sebastianbergmann** [comment]
No feedback, closing.
