### ISSUE TITLE
creating mock phpunit discrepency in mocked namespace and the original one 

### ISSUE THREAD

**Issue by joeprintfffffff** [sebastianbergmann/phpunit-mock-objects#403]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.13
| PHP version         | 7.2
| Installation Method | Composer 

I have function like this:

```
    class Bar{
        public function a():Foo{
        .
        .
        .
        }
    }

```
now I am trying to create a mock for the class Bar with php unit test

```
        $mockedBar = $this->getMockBuilder(Bar::class)
         ->getMock()
         ->method('a')
         ->willReturn(new FakeFoo());
```

but when I am calling method `a` I am getting an error that method `a` return type must be instance of Foo not Mocked_blahblah.

unfortunately class Bar don't use any interface and the system is very big and I can't create an interface cause it make huge refactor in my codes;
is there any way to disable return type of function `a` in mocked object?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
Also note that PHPUnit 6.0 is no longer supported. The only supported versions of PHPUnit at this time are PHPUnit 6.5 and PHPUnit 7.0.

**Comment by joeprintfffffff** [comment]
thank you for fast reply.
here its an example:
```
class A
{
    public function b():B
    {
        echo "i am from class A function b";
    }
}
```

```
class B
{

}
```
```

class FakeB
{
}
```

```
class ATest extends TestCase
{
    public function testSayHi(){
        $mockedA = $this->getMockBuilder(A::class)
            ->getMock();
        $mockedA->method('b')->willReturn(new FakeB());
        $mockedA->b();
    }
}
```

**Comment by joeprintfffffff** [comment]
I also tested with phpunit 7 and I got the same error.
I want to know is there any way to ignore return type checking

**Comment by sebastianbergmann** [comment]
I do not understand what you are trying to report. And, no, there is no way to ignore return type declarations.

**Comment by githoober** [comment]
I have the same problem. Does anyone maybe know if it was fixed in the latest version of PHPUnit, because we for now are stuck with PHPUnit 5.
