### ISSUE TITLE
Mocks created with createMock returns other mocks based on return type of SUT

### ISSUE THREAD

**Issue by Gamesh** [sebastianbergmann/phpunit-mock-objects#404]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0
| PHP version         | 7.1.13
| Installation Method | Composer

phpunit test doubles documentation states:
https://phpunit.de/manual/current/en/test-doubles.html

> By default, all methods of the original class are replaced with a dummy implementation that just returns null (without calling the original method).

but in reality when using createMock, this behavior changed and mocked methods now return a mock of a return type if a method has a return type and its an object, otherwise null.
If return type is nullable object, it return null.

```php
class Foo
{
    public function returnsVoid(): void
    {
        return;
    }

    public function returnsNull()
    {
        return null;
    }

    public function returnsNullableObject(): ?stdClass
    {
        return new stdClass();
    }

    public function returnsObject(): stdClass
    {
        return new stdClass();
    }

    public function returnsString(): string
    {
        return 'foo';
    }

    public function returnsInt(): int
    {
        return 123;
    }
}

class MyTestCase extends TestCase
{
    public function testReturnTypes()
    {
        $mock = $this->createMock(Foo::class);
        self::assertNull($mock->returnsVoid());
        self::assertNull($mock->returnsNull());
        self::assertNull($mock->returnsNullableObject());
        self::assertInstanceOf(stdClass::class, $mock->returnsObject());
        self::assertInstanceOf(MockObject::class, $mock->returnsObject());
        self::assertSame('', $mock->returnsString());
        self::assertSame(0, $mock->returnsInt());
    }
}
```
Output:
```
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.



Time: 167 ms, Memory: 4.00MB

OK (1 test, 7 assertions)
```

Since i didn't specify any method return values, i expected all methods to return null, but it returns a mock of \stdClass which is unexpected.
Is it a bug or an undocumented feature?

**Comment by sebastianbergmann** [comment]
This is not a bug.

**Comment by Gamesh** [comment]
@sebastianbergmann can we update the documentation to clarify this new behavior?

**Comment by sebastianbergmann** [comment]
Sure, just send a pull request for the documentation.

[Here](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Invocation/StaticInvocation.php#L136) you can see the return values that are generated based on the return type declaration of the stubbed method.

**Comment by Gamesh** [comment]
@sebastianbergmann but the phpunit documentation repository is read-only, can't create a pull request

**Comment by sebastianbergmann** [comment]
You are looking at the wrong repository: https://github.com/sebastianbergmann/phpunit-documentation-english
