### ISSUE TITLE
BC Break in 6.1.0

### ISSUE THREAD

**Issue by webimpress** [sebastianbergmann/phpunit-mock-objects#413]
| Q                            | A
| -----------------------------| ---------------
| phpunit-mock-objects version | 6.1.0
| PHPUnit version              | N/A
| PHP version                  | 7.1
| Installation Method          | Composer

Release 6.1.0 contains not documented BC Break introduced in:
https://github.com/sebastianbergmann/phpunit-mock-objects/commit/01599f39c2fe7fab44c45a5f1c0f9c091b362385#diff-23a11370e5d9135e43d63b1e654c81b4

- there is added new method in interface, so all classes which implements that interface MUST be updated on updating that library.

Does this library follow [symver](https://semver.org)?

**Comment by sebastianbergmann** [comment]
There is no BC break here: the `PHPUnit_Framework_MockObject_MockObject` interface is only implemented by the classes that are generated by the code generator that is part of this component.
