### ISSUE TITLE
Global constants as default parameter values are not handled correctly in namespace

### ISSUE THREAD

**Issue by csiz0** [sebastianbergmann/phpunit-mock-objects#420]
| Q                            | A
| -----------------------------| ---------------
| phpunit-mock-objects version | 5.0.7
| PHPUnit version              | PHPUnit 6.5.8 by Sebastian Bergmann and contributors.
| PHP version                  | PHP 7.1.15-1+ubuntu16.04.1+deb.sury.org+2 (cli) (built: Mar  6 2018 11:10:13) ( NTS )
| Installation Method          | Composer / PHAR both

Regarding to this issue:
https://github.com/sebastianbergmann/phpunit-mock-objects/issues/419
https://github.com/sebastianbergmann/phpunit-mock-objects/compare/5.0.6...5.0.7

Using a namespace and let use the default parameter value occurs the fallback to global namespace going to be fail.

```php
<?php

namespace Vendor\Foo;

use PHPUnit\Framework\TestCase;

class Blah {
	protected function helper(int $i = PHP_INT_MIN) {
		return $i;
	}

	public function sut() {
		return $this->helper();
	}
}

class BlahTest extends TestCase {
	public function testSutCallsHelper() {
		$expected = 999;
		$mock = $this->getMockBuilder(Blah::class)
			->setMethods(['helper'])
			->getMock();
		$mock->expects($this->once())
			->method('helper')
			->willReturn($expected);

		$this->assertEquals($expected, $mock->sut());
	}
}
```

```
Error : Undefined constant 'Vendor\Foo\PHP_INT_MIN'
```

It was good in the previous version(phpunit/phpunit-mock-objects:5.0.6) without the integer parameter type declaration.

**Comment by sebastianbergmann** [comment]
The problem here is that `ReflectionParameter::getDefaultValueConstantName()` returns `Vendor\Foo\PHP_INT_MIN`, which is arguably correct.

Here is a simplified example:

```php
<?php
namespace vendor;

class C
{
    public function m(int $i = PHP_INT_MIN)
    {
    }
}

$rm = new \ReflectionMethod(C::class, 'm');

foreach ($rm->getParameters() as $rp) {
    print $rp->getDefaultValueConstantName() . PHP_EOL;
}
```
```
vendor\PHP_INT_MIN
```
If you use a global constant, and built-in constants such as `PHP_INT_MIN` are global, within namespaced code then you should prefix them with `\`.

**Comment by csiz0** [comment]
I have vendor libraries with this function like this:

```php
namespace vendor;

public function foo($i = PHP_INT_MIN){}

public function bar($errorTypes = E_ALL){}
```

So I can't touch them, furthermore those are correct.

http://php.net/manual/en/language.namespaces.fallback.php#language.namespaces.fallback

In this case the fallback doesn't work and I can't mock them.

Probably this can affect some others too.

**Comment by beporter** [comment]
I can confirm I'm seeing this same thing now. I've worked around it for now by changing the method signature to prefix the constant with a backslash and force it to be global:

`function foo($i = \PHP_MAX_INT){...}`
