### ISSUE TITLE
Archive the project?

### ISSUE THREAD

**Issue by keradus** [sebastianbergmann/phpunit-mock-objects#425]
As project was merged into PHPUnit, maybe it's worth to mark it as archived ?

**Comment by sebastianbergmann** [comment]
This will happen in February when PHPUnit 8 is released and support for PHPUnit 6.5 ends.

**Comment by keradus** [comment]
yet, recently discovered bug in this lib is gonna be fixed in PHPUnit 7.2, instead here, so PHPUnit 7.1 or 6.5 won't benefit from it.
keeping the repo open, yet don't merge fixes here, doesn't provide big value :(

**Comment by sebastianbergmann** [comment]
If I get pull requests for this (for PHPUnit 6.5) I will review/merge them.

**Comment by keradus** [comment]
here you go ;)
https://github.com/sebastianbergmann/phpunit-mock-objects/pull/424

**Comment by keradus** [comment]
go away bot ;)

**Comment by keradus** [comment]
wait wait bot, wait for February ;)
