### ISSUE TITLE
Visibility for magic method __sleep must be public. Found: private

### ISSUE THREAD

**Issue by paulrooney** [sebastianbergmann/phpunit-mock-objects#429]
https://github.com/sebastianbergmann/phpunit-mock-objects/blob/0dfddc236629eb7ead4df2dfa3d79d548e011a3b/tests/_fixture/SingletonClass.php#L17

http://php.net/manual/en/language.oop5.magic.php#object.sleep

**Comment by sebastianbergmann** [comment]
This ticket makes no sense (and this project is dead and will soon be archived).
