### ISSUE TITLE
Enable stack traces in failure messages

### ISSUE THREAD

**Issue by dharkness** [sebastianbergmann/phpunit-mock-objects#64]
Since the method expectations are verified after the test method completes, the entire stack trace is stripped (and would be useless if shown). When assertions fail, the exception is thrown on the line where the assertion occurs. I'd really like that behavior with method expectations.

If the invocation matchers were to create an exception when they are defined, they would capture this information. When verify() fails, the exception could be thrown instead of creating a new one.

The other option is to capture the file/line using debug_backtrace() and throw a SyntheticError instead, but that wouldn't be as complete.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
