### ISSUE TITLE
Make a test fail if a mocked method is not expected to be invoked (Reopen)

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/phpunit-mock-objects#65]
Hi, i found this issue in the closed section : https://github.com/sebastianbergmann/phpunit-mock-objects/issues/9

I reopened it because i consider it pretty major.

Here is an example, i want to test this :

``` PHP
class UniverseController
{
   public function doMaintenance(Universe $universe)
   {
      if (!$universe->peopleIsHappy())
      {
         $universe->giveJoy();
      }
   }
}
//Universe object
class Universe
{
   public function peopleIsHappy()
   {
      return true;
   }

   public function giveJoy()
   {
      //Give Joy
   }

   public function killEveryone()
   {
      die ("Everyone's dead now.");
   }
}
```

Now here's the test for the doMaintenance Method.

``` PHP
class UniverseControllerTest extends PHPUnit_Framework_TestCase
{
   public function testDoMaintenance()
   {
      $universeMock = $this->getMock("Universe");

      $universeMock->expects($this->once())->method("peopleIsHappy")->will($this->returnValue(false));
      $universeMock->expects($this->once())->method("giveJoy");

      $subject = new UniverseController();

      $subject->doMaintenance($universeMock);
   }
}
```

So if you run it as is, now, everything is fine.

Now imagine there's a troll that edits the UniverseController code and accidentally calls the killEveryone method as in this :

``` PHP
class UniverseController
{
   public function doMaintenance(Universe $universe)
   {
      if (!$universe->peopleIsHappy())
      {
         $universe->giveJoy();
      }
      $universe->killEveryone();
   }
}
```

You can confirm that it's a terrible error.  Now rerun the test, still passes. Even though the $universe is a mock, it's really dangerous to ignore "unexpected" invocations.

The same thing happen if you take the other way around, if initially the doMaintenance() method behavior WAS to killEveryone() and you forget to expect it, the test will run, and someone come and see this line makes no sense, remove it and tests still good.  So basically you can change the "contract" of a method without breaking tests.

So to me it is clear the test SHOULD fail, and i don't really understand the argument emitted in the issue i linked above.  If it breaks a lot of test to fail unexpected mocked methods calls, then i'd say the test aren't really viable, they're assuming a mocked method call to return null when not expected at all.

If it would be too big to change this, maybe there could be a sort of "strict" mock that would NOT allow unexpected methods to be called.

I checked the code of the PHPUnit_Framework_MockObject_InvocationMocker::invoke method and it clearly isn't trivial to make sure the $invocation->methodName has at least once matcher attached to it, but my example above shows a clear flaw in the mocking system.

What do you think?

**Comment by lackovic10** [comment]
This is an old issue, but also :+1: from me for @ghost. I think it would be great to be able to create a mock object with a flag `$strict`, which would make a test fail if a method call is not expected, or even throw an exception. Has anything similar been done recently ??

**Comment by sylfabre** [comment]
@edorian Would you still consider a PR with a method `$mock->allowUnexpectedInvocation(true / false);` which would set a `$allowUnexpectedInvocation` property (`true` as default value) used near line 145 of class `PHPUnit_Framework_MockObject_InvocationMocker`

![image](https://cloud.githubusercontent.com/assets/3177556/18175003/f611f2b0-706f-11e6-90a9-7bc7a212f6cc.png)
to
![image](https://cloud.githubusercontent.com/assets/3177556/18175086/393e7b94-7070-11e6-9b4f-8d4167d2340b.png)

**Comment by lennerd** [comment]
Sad to see this closed as this could be a part of the MockBuilder. 👍

**Comment by emil-nasso** [comment]
Has anything changed in recent phpunit versions that makes something in the line of what @sylfabre showed possible?

**Comment by sylfabre** [comment]
@emil-nasso I've added this to our backlog, I'll try to make a PR once we're done with our upgrade to PHP

**Comment by emil-nasso** [comment]
@sylfabre That is great news, i wish i could buy you a beer or even give you a kiss. :)

**Comment by emil-nasso** [comment]
Can i see the backlog anywhere or the status of this issue?

**Comment by amorimjuliana** [comment]
Any news about this?

**Comment by emil-nasso** [comment]
Is this present in phpunit yet? Can i track it anywhere?

**Comment by amorimjuliana** [comment]
Any news about this?
