### ISSUE TITLE
onConsecutiveCalls takes array, or similar function that takes one

### ISSUE THREAD

**Issue by MarkRoddy** [sebastianbergmann/phpunit-mock-objects#79]
The onConsecutiveCalls() method takes a variable number of arguments, and it would be useful if it could also take a single argument that was an array of values that should be consecutively returned.  This is especially useful if you have a set of similar tests and want to set up a stub to share between them, but they need to return different values.  Something like:

```php
    class SomeTest extends PHPUnit_Framework_TestCase {
        public function createStubSomeObj($retvals) {
            $stub = $this->getMockBuilder("SomeObj")
                ->setMethods(array("foo"))
                ->getMock();
            $sut->expects($this->any())
                ->method('foo') 
            ->will($this->onConsecutiveCalls($retvals));
   }
```

Right now to accomplish this you need to use call_user_func_array on $this->onConsecutiveCalls which is confusing to look and drops the use of the fluent interface.

**Comment by sebastianbergmann** [comment]
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian
